// example-site/svelte/src/routes/+page.svelte
<script lang="ts">
	import HomeTemplate from '../components/04-templates/HomeTemplate.svelte';
	import type { PageProps } from './$types';

	const { data }: PageProps = $props();
</script>

<svelte:head>
	<title>The Meal Place - [SVELTE] The Storybook Dependency Previews Example Site</title>
	<meta
		name="description"
		content="This is an example site to demonstrate the dependency preview addon in a realistic environment."
	/>
</svelte:head>

<HomeTemplate featuredMeals={data.featuredMeals} />

// example-site/solid/src/routes/index.tsx
import { Title } from '@solidjs/meta'
import { HomeTemplate } from '../components/04-templates/HomeTemplate'
import { featuredMealsData } from 'example-site-shared/data'

export default function Home() {
	return (
		<>
			<Title>
				The Meal Place - The Storybook Dependency Previews Example Site
			</Title>
			<HomeTemplate featuredMeals={featuredMealsData} />
		</>
	)
}
