// example-site/preact/src/components/03-organisms/SiteFrameOrganism.tsx
import type { ComponentChildren } from 'preact'
import { HeaderOrganism } from './HeaderOrganism'
import { FooterOrganism } from './FooterOrganism'

export interface PropsForSiteFrameOrganism {
	children?: ComponentChildren
}

export function SiteFrameOrganism({ children }: PropsForSiteFrameOrganism) {
	return (
		<div class="SiteFrameOrganism grid grid-rows-[auto_1fr_auto] min-h-full">
			<HeaderOrganism />
			<div class="flex-1 grid">{children}</div>
			<FooterOrganism />
		</div>
	)
}

// example-site/svelte/src/components/03-organisms/SiteFrameOrganism.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import HeaderOrganism from './HeaderOrganism.svelte';
	import FooterOrganism from './FooterOrganism.svelte';

	export interface PropsForSiteFrameOrganism {
		children?: Snippet;
	}

	const { children }: PropsForSiteFrameOrganism = $props();
</script>

<div class="SiteFrameOrganism grid min-h-full grid-rows-[auto_1fr_auto]">
	<HeaderOrganism />
	<div class="grid flex-1">
		{@render children?.()}
	</div>
	<FooterOrganism />
</div>
