// example-site/svelte/src/components/04-templates/CardListTemplate.svelte
<script lang="ts">
	import { H, Level } from 'svelte-headings';
	import SiteFrameOrganism from '../03-organisms/SiteFrameOrganism.svelte';
	import ScreenPaddingAtom from '../01-atoms/ScreenPaddingAtom.svelte';
	import CardListingOrganism from '../listings/card/CardListingOrganism.svelte';
	import type { PropsForCardMolecule } from '../listings/card/CardMolecule.svelte';

	export interface PropsForCardListTemplate {
		title: string;
		introText?: string;
		cardList?: Array<PropsForCardMolecule>;
	}

	const { title, cardList, introText }: PropsForCardListTemplate = $props();
</script>

<SiteFrameOrganism>
	<ScreenPaddingAtom padVertical>
		<Level class="MealListTemplate grid gap-4">
			<H class="text-4xl font-bold">{title}</H>
			<p class="mb-2">{introText}</p>
			<CardListingOrganism cards={cardList} />
		</Level>
	</ScreenPaddingAtom>
</SiteFrameOrganism>

// example-site/src/components/04-templates/CardListTemplate.tsx
import { H, Section } from 'react-headings'
import { CardListingOrganism } from '../listings/card/CardListingOrganism'
import { SiteFrameOrganism } from '../03-organisms/SiteFrameOrganism'
import { ScreenPaddingAtom } from '../01-atoms/ScreenPaddingAtom'
import type { PropsForCardMolecule } from '../listings/card/CardMolecule'

export interface PropsForCardListTemplate {
	title: string
	introText?: string
	cardList?: Array<PropsForCardMolecule>
}

export function CardListTemplate({
	title,
	introText,
	cardList,
}: PropsForCardListTemplate) {
	return (
		<SiteFrameOrganism>
			<ScreenPaddingAtom padVertical>
				<div className="MealListTemplate grid gap-4">
					<Section component={<H className="text-4xl font-bold">{title}</H>}>
						<p className="mb-2">{introText}</p>
						<CardListingOrganism cards={cardList} />
					</Section>
				</div>
			</ScreenPaddingAtom>
		</SiteFrameOrganism>
	)
}
