// example-site/angular/src/components/04-templates/CardListTemplate.component.ts
import { Component, input } from '@angular/core';
import { SiteFrameOrganismComponent } from '../03-organisms/SiteFrameOrganism.component';
import { ScreenPaddingAtomComponent } from '../01-atoms/ScreenPaddingAtom.component';
import { CardListingOrganismComponent } from '../listings/card/CardListingOrganism.component';
import type { PropsForCardMolecule } from '../listings/card/CardMolecule.component';

@Component({
	selector: 'card-list-template',
	template: `
		<site-frame-organism>
			<screen-padding-atom class="py-8">
				<div class="MealListTemplate grid gap-4">
					<h1 class="text-4xl font-bold">{{ title() }}</h1>
					<p class="mb-2">{{ introText() }}</p>
					<card-listing-organism [cards]="cardList()" [view]="view()" />
				</div>
			</screen-padding-atom>
		</site-frame-organism>
	`,
	standalone: true,
	imports: [SiteFrameOrganismComponent, ScreenPaddingAtomComponent, CardListingOrganismComponent],
})
export class CardListTemplateComponent {
	title = input<string>('');
	introText = input<string>('');
	cardList = input<Array<PropsForCardMolecule>>([]);
	view = input<'grid' | 'list'>('grid');
}

<app-site-frame-organism>
	<app-screen-padding-atom [padVertical]="true">
		<div class="CardListTemplate grid gap-4">
			<h2 class="text-3xl font-bold">{{ title() }}</h2>
			@if (introText()) {
				<p>{{ introText() }}</p>
			}
			<app-card-listing-organism [cards]="cardList()" />
		</div>
	</app-screen-padding-atom>
</app-site-frame-organism>

// example-site/src/components/04-templates/CardListTemplate.tsx
import { H, Section } from 'react-headings'
import { CardListingOrganism } from '../listings/card/CardListingOrganism'
import { SiteFrameOrganism } from '../03-organisms/SiteFrameOrganism'
import { ScreenPaddingAtom } from '../01-atoms/ScreenPaddingAtom'
import type { PropsForCardMolecule } from '../listings/card/CardMolecule'

export interface PropsForCardListTemplate {
	title: string
	introText?: string
	cardList?: Array<PropsForCardMolecule>
}

export function CardListTemplate({
	title,
	introText,
	cardList,
}: PropsForCardListTemplate) {
	return (
		<SiteFrameOrganism>
			<ScreenPaddingAtom padVertical>
				<div className="MealListTemplate grid gap-4">
					<Section component={<H className="text-4xl font-bold">{title}</H>}>
						<p className="mb-2">{introText}</p>
						<CardListingOrganism cards={cardList} />
					</Section>
				</div>
			</ScreenPaddingAtom>
		</SiteFrameOrganism>
	)
}
