// example-site/vue/components/04-templates/HomeTemplate.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Meal } from 'example-site-shared/data'
import SiteFrameOrganism from '../03-organisms/SiteFrameOrganism.vue'
import HeroBlockOrganism from '../03-organisms/HeroBlockOrganism.vue'
import ExternalLinkAtom from '../01-atoms/ExternalLinkAtom.vue'
import ScreenPaddingAtom from '../01-atoms/ScreenPaddingAtom.vue'
import CardListingOrganism from '../listings/card/CardListingOrganism.vue'
import type { PropsForCardMolecule } from '../listings/card/CardMolecule.vue'

export interface PropsForHomeTemplate {
	featuredMeals: Array<Meal>
}

const { featuredMeals } = defineProps<PropsForHomeTemplate>()

const featureMeal = computed(() => featuredMeals[0])
const cards = computed(() =>
	featuredMeals.slice(1).map(
		(meal): PropsForCardMolecule => ({
			title: meal.name,
			description: meal.area,
			imgSrc: meal.image,
			href: '/meal/$mealId',
			hrefParams: { mealId: meal.id },
		}),
	),
)
</script>

<template>
	<SiteFrameOrganism>
		<div class="HomeTemplate">
			<HeroBlockOrganism :imgSrc="featureMeal?.image">
				<template #title>
					Welcome to the
					<br />
					<ExternalLinkAtom
						href="https://github.com/Dan503/storybook-addon-dependency-previews"
					>
						Storybook Dependency Previews
					</ExternalLinkAtom>
					<br />
					example site
				</template>
				<p>
					This is an example site to demonstrate the dependency preview addon in
					a realistic environment.
				</p>
			</HeroBlockOrganism>
			<ScreenPaddingAtom padVertical>
				<h2 class="mb-4 text-2xl font-bold">Featured meals:</h2>
				<CardListingOrganism :cards="cards" />
			</ScreenPaddingAtom>
		</div>
	</SiteFrameOrganism>
</template>

// example-site/svelte/src/components/04-templates/HomeTemplate.svelte
<script lang="ts">
	import type { Meal } from 'example-site-shared/data';
	import { H, Level } from 'svelte-headings';
	import SiteFrameOrganism from '../03-organisms/SiteFrameOrganism.svelte';
	import HeroBlockOrganism from '../03-organisms/HeroBlockOrganism.svelte';
	import ExternalLinkAtom from '../01-atoms/ExternalLinkAtom.svelte';
	import ScreenPaddingAtom from '../01-atoms/ScreenPaddingAtom.svelte';
	import CardListingOrganism from '../listings/card/CardListingOrganism.svelte';

	export interface PropsForHomeTemplate {
		featuredMeals: Array<Meal>;
	}

	const { featuredMeals }: PropsForHomeTemplate = $props();
	const [featureMeal, ...otherMeals] = $derived(featuredMeals);
</script>

<SiteFrameOrganism>
	<div class="HomeTemplate">
		<HeroBlockOrganism imgSrc={featureMeal.image}>
			{#snippet title()}
				Welcome to the
				<br />
				<ExternalLinkAtom href="https://github.com/Dan503/storybook-addon-dependency-previews">
					Storybook Dependency Previews
				</ExternalLinkAtom>
				<br />
				example site
			{/snippet}

			<p>
				This is an example site to demonstrate the dependency preview addon in a realistic
				environment.
			</p>
		</HeroBlockOrganism>
		<ScreenPaddingAtom padVertical>
			<Level>
				<H class="mb-4 text-2xl font-bold">Featured meals:</H>
				<CardListingOrganism
					cards={otherMeals.map((c) => ({
						title: c.name,
						description: c.area,
						imgSrc: c.image,
						href: '/meal/$mealId',
						hrefParams: { mealId: c.id }
					}))}
				/>
			</Level>
		</ScreenPaddingAtom>
	</div>
</SiteFrameOrganism>
