// example-site/angular/src/components/zz-meta-components/formDataPreview/FormDataPreviewAtom.component.ts
import { Component, input } from '@angular/core';

@Component({
	selector: 'form-data-preview-atom',
	template: ` <pre class="overflow-auto"><code>{{ stringify(formValues()) }}</code></pre> `,
	standalone: true,
	imports: [],
})
export class FormDataPreviewAtomComponent {
	class = input<string>('');
	formValues = input<any>({});
	stringify = (obj: any) => JSON.stringify(obj, null, 3);
}

// example-site/react/src/components/forms/FormDataPreview/FormDataPreviewAtom.tsx
import { getInput } from '@formisch/react'
import type { Schema } from '@formisch/react'
import type { WithForm } from '../FormTypes'

export function FormDataPreviewAtom<TSchema extends Schema>({
	form,
}: WithForm<TSchema>) {
	const formValues = getInput(form)

	return (
		<pre className="overflow-auto">
			<code>{JSON.stringify(formValues, null, 3)}</code>
		</pre>
	)
}
