// example-site/react/src/components/forms/FormDataPreview/FormDataMolecule.tsx
import { FormDataPreviewAtom } from './FormDataPreviewAtom'
import type { Schema } from '@formisch/react'
import type { ReactNode } from 'react'
import type { WithForm } from '../FormTypes'

interface PropsForFormDataWrapper<
	TSchema extends Schema,
> extends WithForm<TSchema> {
	children?: ReactNode
}

export function FormDataMolecule<TSchema extends Schema>({
	form,
	children,
}: PropsForFormDataWrapper<TSchema>) {
	return (
		<div className="grid gap-2">
			{children}
			<FormDataPreviewAtom form={form} />
		</div>
	)
}

// example-site/solid/src/components/forms/FormDataPreview/FormDataMolecule.tsx
import { FormDataPreviewAtom } from './FormDataPreviewAtom'
import type { FormSchema } from '@formisch/solid'
import type { WithForm } from '../FormTypes'
import type { JSX } from 'solid-js'

interface PropsForFormDataWrapper<
	TSchema extends FormSchema,
> extends WithForm<TSchema> {
	children?: JSX.Element
}

export function FormDataMolecule<TSchema extends FormSchema>(
	props: PropsForFormDataWrapper<TSchema>,
) {
	return (
		<div class="grid gap-2">
			{props.children}
			<FormDataPreviewAtom form={props.form} />
		</div>
	)
}
