// example-site/angular/src/components/forms/ErrorMessages/ErrorBlockOrganism.component.ts
import { Component, input } from '@angular/core';
import { ErrorListMoleculeComponent } from './ErrorListMolecule.component';

@Component({
	selector: 'error-block-organism',
	host: { class: 'block', role: 'alert' },
	template: `
		@if (errors().length > 0) {
			<div [class]="'ErrorBlockOrganism rounded-xl bg-red-100 px-4 pt-2 ' + class()">
				<h2 class="border-b-2 border-red-800 pb-1 text-2xl font-bold">
					Please resolve the following errors
				</h2>
				<div class="pt-3 pb-4">
					<error-list-molecule [errors]="errors()" />
				</div>
			</div>
		}
	`,
	standalone: true,
	imports: [ErrorListMoleculeComponent],
})
export class ErrorBlockOrganismComponent {
	class = input<string>('');
	errors = input<Array<string | Error>>([]);
}

@if (errors().length) {
	<div class="ErrorBlockOrganism rounded-lg border-2 border-red-300 bg-red-50 p-4 grid gap-2">
		<p class="font-bold text-red-700">{{ title() }}</p>
		<app-error-list-molecule [errors]="errors()" />
	</div>
}

// example-site/react/src/components/forms/ErrorMessages/ErrorBlockOrganism.tsx
import { clsx } from 'clsx'
import { ErrorListMolecule } from './ErrorListMolecule'

export interface PropsForErrorBlockOrganism {
	errors: Array<string | Error>
}

export function ErrorBlockOrganism({ errors }: PropsForErrorBlockOrganism) {
	return (
		<div
			role="alert"
			className={clsx('bg-red-100 px-4 pt-2 rounded-xl', {
				absolute: errors.length === 0,
			})}
		>
			{errors.length > 0 && (
				<div>
					<h2 className="text-2xl font-bold border-b-2 border-red-800 pb-1">
						Please resolve the following errors
					</h2>
					<div className="pt-3 pb-4">
						<ErrorListMolecule errors={errors} />
					</div>
				</div>
			)}
		</div>
	)
}
