// example-site/angular/src/components/forms/ErrorMessages/ErrorMessageAtom.component.ts
import { Component, input } from '@angular/core';

@Component({
	selector: 'error-message-atom',
	template: `
		<p [class]="'ErrorMessageAtom text-red-900 font-bold leading-none ' + class()">
			{{ errorObject()?.message ?? errorString() ?? 'An error occurred' }}
		</p>
	`,
	standalone: true,
	imports: [],
})
export class ErrorMessageAtomComponent {
	class = input<string>('');
	errorString = input<string>();
	errorObject = input<Error>();
}

// example-site/react/src/components/forms/ErrorMessages/ErrorMessageAtom.tsx
export interface PropsForErrorMessageAtom {
	error: string | Error
}

export function ErrorMessageAtom({ error }: PropsForErrorMessageAtom) {
	return (
		<p
			key={typeof error === 'string' ? error : error.message}
			className="text-red-900 font-bold leading-none"
		>
			{typeof error === 'string' ? error : error.message}
		</p>
	)
}
