// example-site/svelte/src/components/listings/compact/CompactListingMolecule.svelte
<script lang="ts">
	import { Level, H } from 'svelte-headings';
	import { getOptionalFullAddress, type LinkAddress } from '$lib/getFullAddress';

	/**
	 * The address is optional — without one the item draws as plain content rather than a link.
	 * Addresses outside this site belong in `ExternalLinkAtom`.
	 */
	export interface PropsForCompactListingMolecule extends Partial<LinkAddress> {
		imageSrc: string;
		title: string;
		description: string;
	}

	const { description, imageSrc, title, href, hrefParams }: PropsForCompactListingMolecule =
		$props();
	const fullAddress = $derived(getOptionalFullAddress(href, hrefParams));
</script>

<!-- A snippet rather than two copies of the markup, so the linked and plain forms cannot drift apart. -->
{#snippet itemContent()}
	<div class="grid grid-cols-[auto_1fr] items-center gap-4">
		<img src={imageSrc} alt="" class="h-15" />
		<Level element="div">
			<H class="text-xl leading-none font-bold">{title}</H>
			<p>{description}</p>
		</Level>
	</div>
{/snippet}

{#if fullAddress}
	<!-- `getFullAddress` calls `resolve` itself, which the rule cannot see through. -->
	<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -->
	<a href={fullAddress} class="block">{@render itemContent()}</a>
{:else}
	{@render itemContent()}
{/if}

// example-site/solid/src/components/listings/compact/CompactListingMolecule.tsx
import { Show } from 'solid-js'
import type { DollarRouteAddress, LinkAddress } from 'example-site-shared/utils'
import { InternalLinkAtom } from '../../01-atoms/InternalLinkAtom'

interface ContentForCompactListing {
	imageSrc: string
	title: string
	description: string
}

/**
 * The address is optional — without one the item draws as plain content rather
 * than a link. Addresses outside this site belong in `ExternalLinkAtom`.
 */
export type PropsForCompactListingMolecule = ContentForCompactListing &
	Partial<LinkAddress<DollarRouteAddress>>

export function CompactListingMolecule(props: PropsForCompactListingMolecule) {
	// A function, so that both branches below draw it from the current values
	// rather than one copy going stale.
	const itemInternals = () => (
		<ItemInternals
			title={props.title}
			imageSrc={props.imageSrc}
			description={props.description}
		/>
	)
	// Show rather than an early return, so that gaining or losing the address
	// swaps between the linked and plain forms. An early return is taken once
	// and cannot be undone.
	return (
		<Show when={props.href} fallback={itemInternals()}>
			{(href) => (
				<InternalLinkAtom href={href()} hrefParams={props.hrefParams}>
					{itemInternals()}
				</InternalLinkAtom>
			)}
		</Show>
	)
}

/**
 * Draws the picture and words of one item, without the link around them.
 *
 * Takes everything but the address, which it does not draw. The wider type
 * would let a caller pass one and see nothing happen.
 */
function ItemInternals(props: ContentForCompactListing) {
	return (
		<div class="grid grid-cols-[auto_1fr] gap-4 items-center">
			<img src={props.imageSrc} alt="" class="h-15" />
			<div>
				<h3 class="text-xl font-bold leading-none">{props.title}</h3>
				<p>{props.description}</p>
			</div>
		</div>
	)
}
