// example-site/svelte/src/routes/contact/+page.svelte
<script lang="ts">
	import ContactTemplate from '../../components/04-templates/ContactTemplate.svelte';
</script>

<svelte:head>
	<title>Contact Us</title>
	<meta
		name="description"
		content="Get in touch with us at The Meal Place! We'd love to hear from you, whether you have questions, feedback, or just want to say hello."
	/>
</svelte:head>

<ContactTemplate />

// example-site/react/src/routes/contact.tsx
import { createFileRoute } from '@tanstack/react-router'
import { ContactTemplate } from '../components/04-templates/ContactTemplate'

export const Route = createFileRoute('/contact')({
	component: RouteComponent,
	head: () => ({
		meta: [
			{
				title: 'Contact Us | The Meal Place',
			},
			{
				name: 'description',
				content: 'Get in touch with The Meal Place team.',
			},
		],
	}),
})

function RouteComponent() {
	return <ContactTemplate />
}
