// example-site/preact/src/pages/CategoriesPage.tsx
import { fetchCategories } from 'example-site-shared/utils'
import { CardListTemplate } from '../components/04-templates/CardListTemplate'
import { getDataOrWait } from '../lib/getDataOrWait'
import { setPageTitle } from '../lib/pageTitle'

export function CategoriesPage() {
	setPageTitle('Meal Categories | The Meal Place')
	const categories = getDataOrWait('categories', fetchCategories)

	return (
		<CardListTemplate
			title="Food Categories"
			introText="Explore what delicious types of food await you!"
			cardList={categories.map((category) => ({
				title: category.strCategory,
				description: category.strCategoryDescription,
				imgSrc: category.strCategoryThumb,
				href: '/categories/:category',
				hrefParams: { category: category.strCategory },
			}))}
		/>
	)
}

// example-site/angular/src/components/05-pages/CategoriesPage.component.ts
import { Component, signal } from '@angular/core';
import type { Category } from 'example-site-shared/data';
import { CardListTemplateComponent } from '../04-templates/CardListTemplate.component';
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils';
import type { PropsForCardMolecule } from '../listings/card/CardMolecule.component';

@Component({
	selector: 'categories-page',
	template: `<card-list-template [cardList]="categories()" [title]="'Categories'" />`,
	standalone: true,
	imports: [CardListTemplateComponent],
})
export class CategoriesPageComponent {
	categories = signal<PropsForCardMolecule[]>([]);
	async ngOnInit() {
		const categoriesData: Category[] = await fetchCategories();
		const categoriesForCard: PropsForCardMolecule[] = categoriesData.map((category) => {
			return {
				title: category.strCategory,
				href: '/categories/$category',
				hrefParams: { category: category.strCategory },
				imgSrc: category.strCategoryThumb,
				description: category.strCategoryDescription,
			} satisfies PropsForCardMolecule;
		});
		this.categories.set(categoriesForCard);
	}
}
