// example-site/react/src/components/forms/FormDataPreview/FormDataPreviewAtom.tsx
import { getInput } from '@formisch/react'
import type { Schema } from '@formisch/react'
import type { WithForm } from '../FormTypes'

export function FormDataPreviewAtom<TSchema extends Schema>({
	form,
}: WithForm<TSchema>) {
	const formValues = getInput(form)

	return (
		<pre className="overflow-auto">
			<code>{JSON.stringify(formValues, null, 3)}</code>
		</pre>
	)
}

// example-site/vue/components/zz-meta-components/FormDataPreview/FormDataPreviewAtom.vue
<script setup lang="ts" generic="TSchema extends Schema">
import { computed } from 'vue'
import { getInput, type Schema } from '@formisch/vue'
import type { WithForm } from '../../forms/FormTypes'

export type PropsForFormDataPreviewAtom<TSchema extends Schema> =
	WithForm<TSchema>

const { form } = defineProps<PropsForFormDataPreviewAtom<TSchema>>()

const formValues = computed(() => getInput(form))
</script>

<template>
	<pre
		class="overflow-auto"
	><code>{{ JSON.stringify(formValues, null, 3) }}</code></pre>
</template>
