// example-site/svelte/src/components/zz-meta-components/FormDataPreview/FormDataPreviewAtom.svelte
<script lang="ts" module>
	import type { WithForm } from '../../forms/FormTypes';
	import { getInput, type Schema } from '@formisch/svelte';

	export type PropsForFormDataPreviewAtom<TSchema extends Schema> = WithForm<TSchema>;
</script>

<script lang="ts" generics="TSchema extends Schema">
	const { form }: PropsForFormDataPreviewAtom<TSchema> = $props();
	const formValues = $derived(getInput(form));
</script>

<pre class="overflow-auto"><code>{JSON.stringify(formValues, null, 3)}</code></pre>

// example-site/vue/components/zz-meta-components/FormDataPreview/FormDataPreviewAtom.vue
<script setup lang="ts" generic="TSchema extends Schema">
import { computed } from 'vue'
import { getInput, type Schema } from '@formisch/vue'
import type { WithForm } from '../../forms/FormTypes'

export type PropsForFormDataPreviewAtom<TSchema extends Schema> =
	WithForm<TSchema>

const { form } = defineProps<PropsForFormDataPreviewAtom<TSchema>>()

const formValues = computed(() => getInput(form))
</script>

<template>
	<pre
		class="overflow-auto"
	><code>{{ JSON.stringify(formValues, null, 3) }}</code></pre>
</template>
