// example-site/preact/src/pages/CategoryMealsPage.tsx
import { useRoute } from 'preact-iso'
import { fetchMealsByCategory } from 'example-site-shared/utils'
import { CardListTemplate } from '../components/04-templates/CardListTemplate'
import { getMealCard } from '../components/listings/card/CardMolecule'
import { setPageTitle } from '../lib/pageTitle'
import { useFetchedData } from '../lib/useFetchedData'

export function CategoryMealsPage() {
	// Read back plainly: the link that built the address escaped the name going
	// in, and preact-iso unescapes it again on the way out, so it arrives here
	// as it was written. Unescaping it a second time would throw on a name
	// carrying a literal percent sign.
	const { params } = useRoute()
	const categoryName = params.category ?? ''

	setPageTitle(`${categoryName} Meals | The Meal Place`)
	const meals = useFetchedData(`meals-in-category:${categoryName}`, () =>
		fetchMealsByCategory(categoryName),
	)
	const mealList = meals.status === 'ready' ? meals.data : []

	return (
		<CardListTemplate
			title={`${categoryName} meals`}
			introText={`Explore the delicious ${categoryName} meals!`}
			isLoading={meals.status === 'waiting'}
			cardList={mealList.map(getMealCard)}
		/>
	)
}

// example-site/lit/src/pages/CategoryMealsPage.lit.ts
import { LitElement, html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { fetchMealsByCategory } from 'example-site-shared/utils'
import { getFetchedData } from '../lib/fetchedData'
import { gridHostStyles } from '../lib/gridHostStyles'
import { getTextFromAddressPiece } from '../lib/addressPiece'
import { setPageTitle } from '../lib/pageTitle'
import { getMealCard } from '../components/listings/card/CardMolecule.lit'
import '../components/04-templates/CardListTemplate.lit'
import './LoadFailurePage.lit'
import './NotFoundPage.lit'

/**
 * The meals in one category.
 *
 * Moving straight from one category to another keeps this element on screen
 * and only changes `categoryInAddress`, so everything is read from that each
 * time the page draws.
 */
@customElement('app-category-meals-page')
export class CategoryMealsPage extends LitElement {
	/** The category's name as it appears in the address, still escaped. */
	@property() categoryInAddress?: string

	static override styles = gridHostStyles

	override render() {
		const categoryName = getTextFromAddressPiece(this.categoryInAddress)
		if (!categoryName) return html`<app-not-found-page></app-not-found-page>`

		setPageTitle(`${categoryName} Meals | The Meal Place`)
		const meals = getFetchedData({
			key: `meals-in-category:${categoryName}`,
			load: () => fetchMealsByCategory(categoryName),
			page: this,
		})
		if (meals.status === 'failed') {
			return html`<app-load-failure-page
				.onTryAgain=${meals.tryAgain}
			></app-load-failure-page>`
		}
		const cardList = meals.status === 'ready' ? meals.data.map(getMealCard) : []
		return html`<app-card-list-template
			.pageTitle=${`${categoryName} meals`}
			.introText=${`Explore the delicious ${categoryName} meals!`}
			.cardList=${cardList}
			?isLoading=${meals.status === 'waiting'}
		></app-card-list-template>`
	}
}

declare global {
	interface HTMLElementTagNameMap {
		'app-category-meals-page': CategoryMealsPage
	}
}
