// example-site/preact/src/pages/HomePage.tsx
import { useEffect, useState } from 'preact/hooks'
import { fetchRandomMealList, type Meal } from 'example-site-shared/utils'
import { HomeTemplate } from '../components/04-templates/HomeTemplate'
import { setPageTitle } from '../lib/pageTitle'

const featuredMealCount = 7

/**
 * The front page.
 *
 * Its meals are a random seven, so they are fetched here in the browser on each
 * visit rather than through `useDataOrWait`. Going through that would have the
 * build ask for them once and write the answer into the file every visitor is
 * served, which would hand everyone the same seven forever. The Angular site's
 * home page does the same thing for the same reason; the three sites that fetch
 * theirs per visit have a server to do it on, and a set of built files does not.
 *
 * `HomeTemplate` draws its frame, welcome text and heading from an empty list,
 * so the written-out file is the page minus its hero picture and cards.
 */
export function HomePage() {
	setPageTitle(
		'The Meal Place - The Storybook Dependency Previews Example Site',
	)
	const [featuredMeals, setFeaturedMeals] = useState<Array<Meal>>([])

	useEffect(() => {
		fetchRandomMealList(featuredMealCount).then(setFeaturedMeals)
	}, [])

	return <HomeTemplate featuredMeals={featuredMeals} />
}

// example-site/lit/src/pages/HomePage.lit.ts
import { LitElement, html } from 'lit'
import { customElement } from 'lit/decorators.js'
import { fetchRandomMealList } from 'example-site-shared/utils'
import { getFetchedData } from '../lib/fetchedData'
import { gridHostStyles } from '../lib/gridHostStyles'
import { setPageTitle } from '../lib/pageTitle'
import '../components/04-templates/HomeTemplate.lit'
import './LoadFailurePage.lit'

const featuredMealCount = 7

/**
 * The front page.
 *
 * Its meals are a random seven, fetched once per visit: coming back to the home
 * page shows the same seven, and a reload picks new ones. While they are on
 * their way the page draws with no meals, which leaves the welcome and the
 * heading in place.
 */
@customElement('app-home-page')
export class HomePage extends LitElement {
	static override styles = gridHostStyles

	override render() {
		setPageTitle(
			'The Meal Place - The Storybook Dependency Previews Example Site',
		)
		const featuredMeals = getFetchedData({
			key: 'featured-meals',
			load: () => fetchRandomMealList(featuredMealCount),
			page: this,
		})
		if (featuredMeals.status === 'failed') {
			return html`<app-load-failure-page
				.onTryAgain=${featuredMeals.tryAgain}
			></app-load-failure-page>`
		}
		const mealList = featuredMeals.status === 'ready' ? featuredMeals.data : []
		return html`<app-home-template
			.featuredMeals=${mealList}
		></app-home-template>`
	}
}

declare global {
	interface HTMLElementTagNameMap {
		'app-home-page': HomePage
	}
}
