// example-site/svelte/src/components/forms/ContactFormOrganism/ContactFormOrganism.decorator.svelte
<script lang="ts">
	import { type ValidationMode } from '@formisch/svelte';
	import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.svelte';
	import ContactFormOrganism from './ContactFormOrganism.svelte';
	import { createContactForm, onContactFormSubmit } from './createContactForm';

	interface DecoratorProps {
		validate?: ValidationMode;
	}

	const { validate }: DecoratorProps = $props();

	const form = $derived(createContactForm(validate));
</script>

<FormDataMolecule {form}>
	<ContactFormOrganism {form} onSubmit={onContactFormSubmit} />
</FormDataMolecule>

// example-site/vue/components/forms/ContactFormOrganism/ContactFormOrganism.decorator.vue
<script setup lang="ts">
import type { ValidationMode } from '@formisch/vue'
import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.vue'
import ContactFormOrganism from './ContactFormOrganism.vue'
import { onContactFormSubmit, useContactForm } from './useContactForm'

interface DecoratorProps {
	validate?: ValidationMode
}

const { validate } = defineProps<DecoratorProps>()

const form = useContactForm(validate)
</script>

<template>
	<FormDataMolecule :form="form">
		<ContactFormOrganism :form="form" :on-submit="onContactFormSubmit" />
	</FormDataMolecule>
</template>
