// example-site/angular/src/components/listings/compact/CompactListingOrganism.component.ts
import { Component, input } from '@angular/core';
import {
	PropsForCompactListingMolecule,
	CompactListingMoleculeComponent,
} from './CompactListingMolecule.component';

@Component({
	selector: 'compact-listing-organism',
	template: `
		<ul
			[class]="
				'CompactListingOrganism grid gap-4 grid-cols-[repeat(auto-fill,minmax(200px,1fr))] ' +
				class()
			"
		>
			@for (card of items(); track card.href) {
				<li>
					<compact-listing-molecule
						[title]="card.title ?? ''"
						[description]="card.description ?? ''"
						[imageSrc]="card.imageSrc ?? ''"
						[href]="card.href ?? ''"
					/>
				</li>
			}
		</ul>
	`,
	standalone: true,
	imports: [CompactListingMoleculeComponent],
})
export class CompactListingOrganismComponent {
	class = input<string>('');
	items = input<Array<Partial<PropsForCompactListingMolecule>>>([]);
}

<div
	class="CompactListingOrganism grid gap-3"
	style="grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))"
>
	@for (item of items(); track item.title) {
		<app-compact-listing-molecule
			[title]="item.title"
			[description]="item.description ?? ''"
			[imageSrc]="item.imageSrc"
			[href]="item.href"
		/>
	}
</div>

// example-site/vue/components/listings/compact/CompactListingOrganism.vue
<script setup lang="ts">
import CompactListingMolecule, {
	type PropsForCompactListingMolecule,
} from './CompactListingMolecule.vue'

export interface PropsForCompactListingOrganism {
	items: Array<PropsForCompactListingMolecule>
}

const { items } = defineProps<PropsForCompactListingOrganism>()
</script>

<template>
	<ul class="CompactListingOrganism gap-4">
		<li v-for="item in items" :key="item.title">
			<CompactListingMolecule
				:imageSrc="item.imageSrc"
				:title="item.title"
				:description="item.description"
			/>
		</li>
	</ul>
</template>

<style scoped>
.CompactListingOrganism {
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
}
</style>
