// example-site/vue/components/listings/card/CardListingOrganism.vue
<script setup lang="ts">
import CardMolecule, { type PropsForCardMolecule } from './CardMolecule.vue'

export interface PropsForCardListingOrganism {
	cards: Array<PropsForCardMolecule> | undefined
}

const { cards } = defineProps<PropsForCardListingOrganism>()
</script>

<template>
	<div class="@container grid">
		<div
			class="CardListingOrganism grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))] gap-6"
		>
			<CardMolecule
				v-for="card in cards"
				:key="card.title"
				:title="card.title"
				:imgSrc="card.imgSrc"
				:description="card.description"
				:href="card.href"
			/>
		</div>
	</div>
</template>

<style scoped>
.CardListingOrganism {
	grid-template-columns: repeat(3, minmax(0, 1fr));

	@container (width < 800px) {
		grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
	}

	@container (width > 1400px) {
		grid-template-columns: repeat(6, minmax(0, 1fr));
	}
}
</style>

// example-site/angular/src/components/listings/card/CardListingOrganism.component.ts
import { Component, input } from '@angular/core';
import { CardMoleculeComponent, type PropsForCardMolecule } from './CardMolecule.component';

@Component({
	selector: 'card-listing-organism',
	template: `
		<div class="@container grid">
			<div class="CardListingOrganism grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))] gap-6">
				@for (card of cards(); track card.href) {
					<card-molecule
						[title]="card.title ?? ''"
						[href]="card.href ?? ''"
						[description]="card.description ?? ''"
						[imgSrc]="card.imgSrc ?? ''"
					/>
				}
			</div>
		</div>
	`,
	styles: `
		.CardListingOrganism {
			grid-template-columns: repeat(3, minmax(0, 1fr));

			@container (width < 800px) {
				grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
			}

			@container (width > 1400px) {
				grid-template-columns: repeat(6, minmax(0, 1fr));
			}
		}
	`,
	standalone: true,
	imports: [CardMoleculeComponent],
})
export class CardListingOrganismComponent {
	cards = input<Array<Partial<PropsForCardMolecule>>>([]);
}

<div class="CardListingOrganism grid gap-6" style="grid-template-columns: repeat(auto-fit, minmax(200px, 1fr))">
	@for (card of cards(); track card.title) {
		<app-card-molecule
			[title]="card.title"
			[imgSrc]="card.imgSrc"
			[description]="card.description"
			[href]="card.href"
		/>
	}
</div>
