// example-site/svelte/src/components/01-atoms/ButtonAtom.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	export interface PropsForButtonAtom {
		type?: 'button' | 'submit' | 'reset';
		onClick?: (event: MouseEvent) => void;
		children?: Snippet;
	}

	const { children, type, onClick }: PropsForButtonAtom = $props();
</script>

<button
	{type}
	onclick={onClick}
	class="ButtonAtom rounded-lg border-2 border-teal-900 bg-teal-200 px-4 py-1 hover:bg-teal-100 focus:bg-teal-100"
>
	{@render children?.()}
</button>

// example-site/react/src/components/01-atoms/ButtonAtom.tsx
import type { ReactNode } from 'react'

export interface PropsForButtonAtom {
	type?: 'button' | 'submit' | 'reset'
	onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void
	children: ReactNode
}

export function ButtonAtom({
	children,
	type = 'button',
	onClick,
}: PropsForButtonAtom) {
	return (
		<button
			type={type}
			onClick={onClick}
			className="bg-teal-200 hover:bg-teal-100 focus:bg-teal-100 border-2 border-teal-900 px-4 py-1 rounded-lg"
		>
			{children}
		</button>
	)
}
