// example-site/svelte/src/components/01-atoms/ScreenPaddingAtom.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	export interface PropsForScreenPaddingAtom {
		children?: Snippet;
		padVertical?: boolean;
	}

	const { children, padVertical = false }: PropsForScreenPaddingAtom = $props();
</script>

<div class={`ScreenPaddingAtom ${padVertical ? 'p-6' : 'px-6'} w-full`}>
	{@render children?.()}
</div>

// example-site/react/src/components/01-atoms/ScreenPaddingAtom.tsx
import type { ReactNode } from 'react'

export interface PropsForScreenPaddingAtom {
	children?: ReactNode
	padVertical?: boolean
}

export function ScreenPaddingAtom({
	children,
	padVertical,
}: PropsForScreenPaddingAtom) {
	return (
		<div className={`ScreenPaddingAtom ${padVertical ? 'p-6' : 'px-6'} w-full`}>
			{children}
		</div>
	)
}
