// example-site/angular/src/components/zz-meta-components/ChildContentAtom.component.ts
import { Component, input } from '@angular/core';

@Component({
	selector: 'child-content-atom',
	template: `
		<div
			class="ChildContentAtom grid min-h-60 place-items-center rounded-md border-2 border-dashed bg-gray-200 p-4 text-black"
		>
			<p>Placeholder child content</p>
		</div>
	`,
	standalone: true,
})
export class ChildContentAtomComponent {
	class = input<string>('');
}

// example-site/src/components/atoms/ChildContentAtom.tsx
export interface PropsForChildContentAtom {}

export function ChildContentAtom({}: PropsForChildContentAtom) {
	return (
		<div className="ChildContentAtom bg-gray-200 border-2 border-dashed rounded-md text-black p-4 min-h-60 grid place-items-center">
			<p>Placeholder child content</p>
		</div>
	)
}
