// example-site/solid/src/components/listings/card/CardMolecule.tsx
import { splitProps } from 'solid-js'
import type { LinkAddress, Meal } from 'example-site-shared/utils'
import { InternalLinkAtom } from '../../01-atoms/InternalLinkAtom'

export type PropsForCardMolecule = {
	title: string
	imgSrc: string
	description: string
} & LinkAddress

/**
 * Builds the card for one meal.
 *
 * Both lists that show meals — the featured ones on the home page and the ones
 * in a category — draw the same card from the same fields, so they share this
 * rather than each writing it out.
 *
 * @param meal - the meal the card stands for
 */
export function getMealCard(meal: Meal): PropsForCardMolecule {
	return {
		title: meal.name,
		description: meal.area,
		imgSrc: meal.image,
		href: '/meal/$mealId',
		hrefParams: { mealId: meal.id },
	}
}

export function CardMolecule(props: PropsForCardMolecule) {
	const [linkAddress, card] = splitProps(props, ['href', 'hrefParams'])
	return (
		<div class="@container grid">
			<InternalLinkAtom
				{...linkAddress}
				class="h-full flex @max-sm:flex-col gap-2 border rounded-2xl overflow-hidden bg-white focus:bg-teal-200 hover:bg-teal-200 hover:shadow-lg hover:transform-[scale(1.02)] transition-all"
			>
				<img
					src={card.imgSrc}
					alt=""
					class="aspect-video @sm:aspect-square @sm:w-40 object-cover"
				/>
				<div class="p-4 w-full">
					<h3 class="text-xl font-bold">{card.title}</h3>
					<p class="line-clamp-4">{card.description}</p>
				</div>
			</InternalLinkAtom>
		</div>
	)
}

// example-site/vue/app/components/listings/card/CardMolecule.vue
<script lang="ts">
import type { Meal } from 'example-site-shared/data'
import type { LinkAddressPropsViaBrackets } from 'example-site-shared/utils'

/**
 * A card that links to a page inside this site.
 *
 * The address arrives as `href` plus `hrefParams` rather than already finished,
 * so `href` only accepts an address the site actually has and a misspelt one
 * fails the type check. Both props are handed straight to `InternalLinkAtom`,
 * which is where the changing piece is filled in.
 *
 * The bracket spelling is the one this site writes: `/meal/[mealId]` is the
 * address `pages/meal/[mealId].vue` answers. The two address props and what they
 * mean come from `LinkAddressPropsViaBrackets` rather than being restated here.
 */
export interface PropsForCardMolecule extends LinkAddressPropsViaBrackets {
	title: string
	imgSrc: string
	description: string
}

/**
 * Builds the card for one meal.
 *
 * Both lists that show meals — the featured ones on the home page and the ones
 * in a category — draw the same card from the same fields, so they share this
 * rather than each writing it out.
 *
 * @param meal - the meal the card stands for
 */
export function getMealCard(meal: Meal): PropsForCardMolecule {
	return {
		title: meal.name,
		description: meal.area,
		imgSrc: meal.image,
		href: '/meal/[mealId]',
		hrefParams: { mealId: meal.id },
	}
}
</script>

<script setup lang="ts">
import InternalLinkAtom from '../../01-atoms/InternalLinkAtom.vue'

const { title, imgSrc, description, href, hrefParams } =
	defineProps<PropsForCardMolecule>()
</script>

<template>
	<div class="CardMolecule @container grid">
		<InternalLinkAtom
			:href="href"
			:hrefParams="hrefParams"
			class="flex h-full gap-2 overflow-hidden rounded-2xl border bg-white transition-all hover:transform-[scale(1.02)] hover:bg-teal-200 hover:shadow-lg focus:bg-teal-200"
		>
			<img :src="imgSrc" alt="" class="aspect-video object-cover" />
			<div class="w-full p-4">
				<h2 class="text-xl font-bold">{{ title }}</h2>
				<p class="line-clamp-4">{{ description }}</p>
			</div>
		</InternalLinkAtom>
	</div>
</template>

<style scoped>
.CardMolecule {
	@container (400px <= width) {
		img {
			width: 200px;
			aspect-ratio: 1 / 1;
		}
	}
	@container (width < 400px) {
		a {
			flex-direction: column;
		}
		img {
			width: 100%;
			aspect-ratio: 16 / 9;
		}
	}
}
</style>
