// example-site/svelte/src/components/02-molecules/MainNavMolecule.svelte
<script>
	import { activeNavItem } from '../../lib/store';
</script>

<nav class="flex flex-row gap-4 font-bold">
	<a href="/" class:underline={$activeNavItem === 'home'}>Home</a>
	<a href="/categories" class:underline={$activeNavItem === 'categories'}>Food categories</a>
	<a href="/contact" class:underline={$activeNavItem === 'contact'}>Contact us</a>
</nav>

// example-site/vue/app/components/02-molecules/MainNavMolecule.vue
<script setup lang="ts">
import { useActiveNavItem } from '../../lib/useActiveNavItem'

export interface PropsForMainNavMolecule {}

const {} = defineProps<PropsForMainNavMolecule>()

const activeNavItem = useActiveNavItem()
</script>

<template>
	<nav class="MainNavMolecule flex flex-row gap-4 font-bold">
		<NuxtLink to="/" :class="{ underline: activeNavItem === 'home' }"
			>Home</NuxtLink
		>
		<NuxtLink
			to="/categories"
			:class="{ underline: activeNavItem === 'categories' }"
			>Food categories</NuxtLink
		>
		<NuxtLink
			to="/contact"
			:class="{ underline: activeNavItem === 'contact' }"
			>Contact us</NuxtLink
		>
	</nav>
</template>
