// example-site/preact/src/index.tsx
import {
	LocationProvider,
	Router,
	Route,
	hydrate,
	prerender as ssr,
} from 'preact-iso'

import { HomePage } from './pages/HomePage'
import { CategoriesPage } from './pages/CategoriesPage'
import { CategoryMealsPage } from './pages/CategoryMealsPage'
import { MealDetailPage } from './pages/MealDetailPage'
import { ContactPage } from './pages/ContactPage'
import { NotFoundPage } from './pages/NotFoundPage'
import { getTitleForPageBeingBuilt } from './lib/pageTitle'
import './app.css'

/*
 * The five addresses every example site carries, written the way preact-iso
 * matches them — a colon in front of the piece that changes. They are the same
 * five the shared package lists as `colonRouteTemplates`, which is what
 * `InternalLinkAtom` checks a link against.
 */
export function App() {
	return (
		<LocationProvider>
			<Router>
				<Route path="/" component={HomePage} />
				<Route path="/categories" component={CategoriesPage} />
				<Route path="/categories/:category" component={CategoryMealsPage} />
				<Route path="/meal/:mealId" component={MealDetailPage} />
				<Route path="/contact" component={ContactPage} />
				<Route default component={NotFoundPage} />
			</Router>
		</LocationProvider>
	)
}

const appRoot =
	typeof window === 'undefined' ? null : document.getElementById('app')
if (appRoot) {
	hydrate(<App />, appRoot)
}

/**
 * Draws one page for the build, and says which pages to write next.
 *
 * The build finds the pages it has not written yet by reading the links in the
 * ones it has, so the list handed back here is what decides how far it goes.
 *
 * The address is not passed in: the build sets it on the global `location`
 * before calling this, which is where preact-iso's location provider reads it
 * from.
 */
export async function prerender() {
	const page = await ssr(<App />)
	const linksFound = page.links ?? new Set<string>()
	return {
		...page,
		head: { title: getTitleForPageBeingBuilt() },
		links: new Set([...linksFound].filter(checkShouldBuildPageAhead)),
	}
}

/**
 * Whether the build should write this page out ahead of anyone asking for it.
 *
 * Every page but a single meal's is written ahead. Meal pages are left out
 * deliberately: the home page links to featured meals, the categories page
 * links to all fourteen categories, and each of those links to every meal in
 * it, so following them all would ask the meal database for around three
 * hundred meals, one after another, on every build. A meal page fetches its own
 * meal when opened instead, and `public/_redirects` tells a static host to
 * serve the site for an address with no file behind it.
 *
 * @param address - a link found in a page the build has just written
 */
function checkShouldBuildPageAhead(address: string): boolean {
	return !address.startsWith('/meal/')
}

// example-site/lit/src/index.ts
import { LitElement, css, html, render, type TemplateResult } from 'lit'
import { customElement } from 'lit/decorators.js'
import { Router } from '@lit-labs/router'
import {
	colonRouteTemplates,
	type ColonRouteTemplate,
	type HrefParams,
} from 'example-site-shared/utils'
import { announceAddressChange } from './lib/addressChange'
import './pages/HomePage.lit'
import './pages/CategoriesPage.lit'
import './pages/CategoryMealsPage.lit'
import './pages/MealDetailPage.lit'
import './pages/ContactPage.lit'
import './pages/NotFoundPage.lit'
import './app.css'

// The router matches addresses with the browser's `URLPattern`, which older
// Safari lacks. The package that adds it is fetched only where it is missing,
// and before the site is drawn, since the router first matches the address as
// soon as the site element is on the page.
const isAddressMatchingMissing = !('URLPattern' in globalThis)
if (isAddressMatchingMissing) await import('urlpattern-polyfill')

/**
 * The page that answers each address, keyed by the address as the router
 * matches it — a colon in front of the piece that changes.
 *
 * Typed against the shared list rather than written out beside the routes, so a
 * page missing for one of the shared addresses, or one listed for an address
 * the shared package does not have, fails the type check.
 *
 * A changing piece reaches its page still escaped, and the page unescapes it.
 */
const pageForAddress: Record<
	ColonRouteTemplate,
	(addressPieces: HrefParams) => TemplateResult
> = {
	'/': () => html`<app-home-page></app-home-page>`,
	'/categories': () => html`<app-categories-page></app-categories-page>`,
	'/categories/:category': ({ category }) =>
		html`<app-category-meals-page
			.categoryInAddress=${category}
		></app-category-meals-page>`,
	'/meal/:mealId': ({ mealId }) =>
		html`<app-meal-detail-page
			.mealIdInAddress=${mealId}
		></app-meal-detail-page>`,
	'/contact': () => html`<app-contact-page></app-contact-page>`,
}

/**
 * The whole site: draws the page that matches the address, and moves to
 * another without reloading when a link inside the site is clicked or the
 * browser's back and forward buttons are used.
 *
 * It draws only the page. Each page draws the site frame, the header and
 * footer, itself.
 */
@customElement('app-site')
export class Site extends LitElement {
	/**
	 * One route per shared address, read off the shared list itself — the same
	 * list the nav and the cards check their links against. An address none of
	 * them matches draws the not-found page.
	 */
	private _router = new Router(
		this,
		colonRouteTemplates.map((path) => ({ path, render: pageForAddress[path] })),
		{
			fallback: {
				render: () => html`<app-not-found-page></app-not-found-page>`,
			},
		},
	)

	static override styles = css`
		:host {
			display: grid;
		}
	`

	override render() {
		return this._router.outlet()
	}

	/** The router asks for a redraw on every move, so this runs after each one. */
	override updated() {
		announceAddressChange()
	}
}

declare global {
	interface HTMLElementTagNameMap {
		'app-site': Site
	}
}

const appRoot = document.getElementById('app')
if (appRoot) render(html`<app-site></app-site>`, appRoot)
