// example-site/solid/src/components/03-organisms/SiteFrameOrganism.tsx
import { HeaderOrganism } from './HeaderOrganism'
import { FooterOrganism } from './FooterOrganism'
import type { JSX } from 'solid-js'

export interface PropsForSiteFrameOrganism {
	children?: JSX.Element
}

export function SiteFrameOrganism({ children }: PropsForSiteFrameOrganism) {
	return (
		<div class="SiteFrameOrganism grid grid-rows-[auto_1fr_auto] min-h-full">
			<HeaderOrganism />
			<div class="flex-1 grid">{children}</div>
			<FooterOrganism />
		</div>
	)
}

// example-site/react/src/components/03-organisms/SiteFrameOrganism.tsx
import type { ReactNode } from 'react'
import { HeaderOrganism } from './HeaderOrganism'
import { FooterOrganism } from './FooterOrganism'

export interface PropsForSiteFrameOrganism {
	children?: ReactNode
}

export function SiteFrameOrganism({ children }: PropsForSiteFrameOrganism) {
	return (
		<div className="SiteFrameOrganism grid grid-rows-[auto_1fr_auto] min-h-full">
			<HeaderOrganism />
			<div className="flex-1 grid">{children}</div>
			<FooterOrganism />
		</div>
	)
}
