// example-site/vue/components/03-organisms/SiteFrameOrganism.vue
<script setup lang="ts">
import HeaderOrganism from './HeaderOrganism.vue'
import FooterOrganism from './FooterOrganism.vue'

export interface PropsForSiteFrameOrganism {}

const {} = defineProps<PropsForSiteFrameOrganism>()
</script>

<template>
	<div class="SiteFrameOrganism grid min-h-full grid-rows-[auto_1fr_auto]">
		<HeaderOrganism />
		<div class="grid flex-1">
			<slot />
		</div>
		<FooterOrganism />
	</div>
</template>

// example-site/react/src/components/03-organisms/SiteFrameOrganism.tsx
import type { ReactNode } from 'react'
import { HeaderOrganism } from './HeaderOrganism'
import { FooterOrganism } from './FooterOrganism'

export interface PropsForSiteFrameOrganism {
	children?: ReactNode
}

export function SiteFrameOrganism({ children }: PropsForSiteFrameOrganism) {
	return (
		<div className="SiteFrameOrganism grid grid-rows-[auto_1fr_auto] min-h-full">
			<HeaderOrganism />
			<div className="flex-1 grid">{children}</div>
			<FooterOrganism />
		</div>
	)
}
