// example-site/angular/src/components/listings/card/CardMolecule.component.ts
import { Component, input } from '@angular/core';
import type { AngularComponentProps } from 'storybook-addon-dependency-previews';

@Component({
	selector: 'card-molecule',
	template: `
		<div [class]="'CardMolecule @container h-full grid ' + class()">
			<a
				[href]="href()"
				class="grid @max-sm:grid-rows-[auto_1fr] @min-sm:grid-cols-[200px_1fr] h-full @min-sm:gap-2 overflow-hidden rounded-2xl border bg-white transition-all hover:transform-[scale(1.02)] hover:bg-teal-200 hover:shadow-lg focus:bg-teal-200"
			>
				<img [src]="imgSrc()" alt="" class="aspect-video object-cover h-full" />
				<div class="w-full p-4">
					<h3 class="text-xl font-bold">{{ title() }}</h3>
					<p class="line-clamp-4">{{ description() }}</p>
				</div>
			</a>
		</div>
	`,
	standalone: true,
	imports: [],
	styles: ``,
})
export class CardMoleculeComponent {
	class = input<string>('');
	title = input<string>('');
	imgSrc = input<string>('');
	description = input<string>('');
	href = input<string>('');
}

export type PropsForCardMolecule = AngularComponentProps<CardMoleculeComponent, 'class'>;

<div class="@container grid">
	<a
		[routerLink]="href()"
		class="h-full flex flex-col gap-2 border rounded-2xl overflow-hidden bg-white focus:bg-teal-200 hover:bg-teal-200 hover:shadow-lg transition-all sm:flex-row"
	>
		<img [src]="imgSrc()" alt="" class="aspect-video object-cover sm:aspect-square sm:w-40" />
		<div class="p-4 w-full">
			<h3 class="text-xl font-bold">{{ title() }}</h3>
			<p class="line-clamp-4">{{ description() }}</p>
		</div>
	</a>
</div>

// example-site/react/src/components/listings/card/CardMolecule.tsx
import { Link } from '@tanstack/react-router'
import { H, Section } from 'react-headings'
import type {
	RouterParams,
	RouterPaths,
} from '../../../utils/routerUtilityTypes'

export interface PropsForCardMolecule {
	title: string
	imgSrc: string
	description: string
	href: RouterPaths
	hrefParams?: RouterParams
}

export function CardMolecule({
	description,
	href,
	hrefParams,
	title,
	imgSrc,
}: PropsForCardMolecule) {
	return (
		<div className="@container grid">
			<Link
				to={href}
				params={hrefParams}
				className="h-full flex @max-sm:flex-col gap-2 border rounded-2xl overflow-hidden bg-white focus:bg-teal-200 hover:bg-teal-200 hover:shadow-lg hover:transform-[scale(1.02)] transition-all"
			>
				<img
					src={imgSrc}
					alt=""
					className="aspect-video @sm:aspect-square @sm:w-40 object-cover"
				/>
				<div className="p-4 w-full">
					<Section component={<H className="text-xl font-bold">{title}</H>}>
						<p className="line-clamp-4">{description}</p>
					</Section>
				</div>
			</Link>
		</div>
	)
}
