// example-site/svelte/src/components/listings/card/CardMolecule.svelte
<script lang="ts">
	import { H, Level } from 'svelte-headings';

	export interface PropsForCardMolecule {
		title: string;
		imgSrc: string;
		description: string;
		href: string;
	}

	const { title, imgSrc, description, href }: PropsForCardMolecule = $props();
</script>

<div class="CardMolecule @container grid">
	<a
		{href}
		class="flex h-full gap-2 overflow-hidden rounded-2xl border bg-white transition-all hover:transform-[scale(1.02)] hover:bg-teal-200 hover:shadow-lg focus:bg-teal-200"
	>
		<img src={imgSrc} alt="" class="aspect-video object-cover" />
		<Level class="w-full p-4">
			<H class="text-xl font-bold">{title}</H>
			<p class="line-clamp-4">{description}</p>
		</Level>
	</a>
</div>

<style>
	.CardMolecule {
		@container (400px <= width) {
			img {
				width: 200px;
				aspect-ratio: 1 / 1;
			}
		}
		@container (width < 400px) {
			a {
				flex-direction: column;
			}
			img {
				width: 100%;
				aspect-ratio: 16 / 9;
			}
		}
	}
</style>

// example-site/react/src/components/listings/card/CardMolecule.tsx
import { Link } from '@tanstack/react-router'
import { H, Section } from 'react-headings'
import type {
	RouterParams,
	RouterPaths,
} from '../../../utils/routerUtilityTypes'

export interface PropsForCardMolecule {
	title: string
	imgSrc: string
	description: string
	href: RouterPaths
	hrefParams?: RouterParams
}

export function CardMolecule({
	description,
	href,
	hrefParams,
	title,
	imgSrc,
}: PropsForCardMolecule) {
	return (
		<div className="@container grid">
			<Link
				to={href}
				params={hrefParams}
				className="h-full flex @max-sm:flex-col gap-2 border rounded-2xl overflow-hidden bg-white focus:bg-teal-200 hover:bg-teal-200 hover:shadow-lg hover:transform-[scale(1.02)] transition-all"
			>
				<img
					src={imgSrc}
					alt=""
					className="aspect-video @sm:aspect-square @sm:w-40 object-cover"
				/>
				<div className="p-4 w-full">
					<Section component={<H className="text-xl font-bold">{title}</H>}>
						<p className="line-clamp-4">{description}</p>
					</Section>
				</div>
			</Link>
		</div>
	)
}
