// example-site/solid/src/components/04-templates/DetailPageTemplate.tsx
import { Show } from 'solid-js'
import type { Meal } from 'example-site-shared/utils'
import { CompactListingOrganism } from '../listings/compact/CompactListingOrganism'
import { SiteFrameOrganism } from '../03-organisms/SiteFrameOrganism'
import { ScreenPaddingAtom } from '../01-atoms/ScreenPaddingAtom'

export interface PropsForDetailPageTemplate {
	meal: Meal | undefined | null
	isLoading?: boolean
}

// The meal is read as `props.meal` and the waiting state is handled with
// `Show` rather than an early return, so that a meal arriving after the first
// draw replaces the "Loading..." message — which is what happens when the page
// is opened by moving to it rather than by loading the address directly.
export function DetailPageTemplate(props: PropsForDetailPageTemplate) {
	return (
		<Show
			when={!props.isLoading && props.meal}
			fallback={<div>Loading...</div>}
		>
			{(meal) => (
				<SiteFrameOrganism>
					<ScreenPaddingAtom padVertical>
						<h1 class="text-3xl font-bold mb-5">{meal().name}</h1>
						<div class="grid gap-4 lg:grid-cols-[2fr_30rem]">
							<div class="grid gap-4 sm:grid-cols-[1fr_2fr]">
								<img src={meal().image} alt={meal().name} class="mt-2" />
								<div>
									<h2 class="text-2xl font-bold">Recipe</h2>
									<p class="whitespace-pre-wrap">{meal().instructions}</p>
								</div>
							</div>
							<div class="grid gap-4 grid-rows-[auto_1fr] items-start">
								<h2 class="text-2xl font-bold">Ingredients</h2>
								<CompactListingOrganism
									items={meal().ingredients.map((x) => ({
										title: x.ingredient,
										description: x.amount,
										imageSrc: x.imageUrl.small,
									}))}
								/>
							</div>
						</div>
					</ScreenPaddingAtom>
				</SiteFrameOrganism>
			)}
		</Show>
	)
}

// example-site/react/src/components/04-templates/DetailPageTemplate.tsx
import { H, Section } from 'react-headings'
import type { Meal } from 'example-site-shared/utils'
import { CompactListingOrganism } from '../listings/compact/CompactListingOrganism'
import { SiteFrameOrganism } from '../03-organisms/SiteFrameOrganism'
import { ScreenPaddingAtom } from '../01-atoms/ScreenPaddingAtom'

export interface PropsForDetailPageTemplate {
	meal: Meal | undefined | null
	isLoading?: boolean
}

export function DetailPageTemplate({
	meal,
	isLoading,
}: PropsForDetailPageTemplate) {
	if (isLoading || !meal) {
		return <div>Loading...</div>
	}

	return (
		<SiteFrameOrganism>
			<ScreenPaddingAtom padVertical>
				<Section
					component={<H className="text-3xl font-bold mb-5">{meal.name}</H>}
				>
					<div className="grid gap-4 lg:grid-cols-[2fr_30rem]">
						<div className="grid gap-4 sm:grid-cols-[1fr_2fr]">
							<img src={meal.image} alt={meal.name} className="mt-2" />
							<div>
								<Section
									component={<H className="text-2xl font-bold">Recipe</H>}
								>
									<p className="whitespace-pre-wrap">{meal.instructions}</p>
								</Section>
							</div>
						</div>
						<div className="grid gap-4 grid-rows-[auto_1fr] items-start">
							<Section
								component={<H className="text-2xl font-bold">Ingredients</H>}
							>
								<CompactListingOrganism
									items={meal.ingredients.map((x) => ({
										title: x.ingredient,
										description: x.amount,
										imageSrc: x.imageUrl.small,
									}))}
								/>
							</Section>
						</div>
					</div>
				</Section>
			</ScreenPaddingAtom>
		</SiteFrameOrganism>
	)
}
