// example-site/react/src/components/01-atoms/ScreenPaddingAtom.tsx
import type { ReactNode } from 'react'

export interface PropsForScreenPaddingAtom {
	children?: ReactNode
	padVertical?: boolean
}

export function ScreenPaddingAtom({
	children,
	padVertical,
}: PropsForScreenPaddingAtom) {
	return (
		<div className={`ScreenPaddingAtom ${padVertical ? 'p-6' : 'px-6'} w-full`}>
			{children}
		</div>
	)
}

// example-site/solid/src/components/01-atoms/ScreenPaddingAtom.tsx
import type { JSX } from 'solid-js'

export interface PropsForScreenPaddingAtom {
	children?: JSX.Element
	padVertical?: boolean
}

export function ScreenPaddingAtom({
	children,
	padVertical,
}: PropsForScreenPaddingAtom) {
	return (
		<div class={`ScreenPaddingAtom ${padVertical ? 'p-6' : 'px-6'} w-full`}>
			{children}
		</div>
	)
}
