// example-site/vue/components/forms/TextFieldMolecule/TextFieldMolecule.decorator.vue
<script setup lang="ts">
import { Field, Form, useForm, type ValidationMode } from '@formisch/vue'
import {
	defaultFirstNameOnlyValues,
	firstNameOnlySchema,
	type FirstNameOnlyOutputData,
} from 'example-site-shared/data'
import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.vue'
import TextFieldMolecule, {
	type PropsForTextFieldMolecule,
} from './TextFieldMolecule.vue'

interface DecoratorProps extends Omit<PropsForTextFieldMolecule, 'field'> {
	validate?: ValidationMode
}

const { label, placeholder, validate } = defineProps<DecoratorProps>()

const form = useForm({
	schema: firstNameOnlySchema,
	initialInput: defaultFirstNameOnlyValues,
	validate,
})

function onSubmit(output: FirstNameOnlyOutputData) {
	alert(JSON.stringify(output, null, 2))
}
</script>

<template>
	<Form id="form" :of="form" @submit="onSubmit">
		<Field :of="form" :path="['firstName']" v-slot="field">
			<FormDataMolecule :form="form">
				<TextFieldMolecule
					:label="label"
					:placeholder="placeholder"
					:field="field"
				/>
			</FormDataMolecule>
		</Field>
	</Form>
</template>

// example-site/svelte/src/components/forms/TextFieldMolecule.decorator.svelte
<script lang="ts">
	import { createForm, useStore } from '@tanstack/svelte-form';
	import TextFieldMolecule, { type PropsForTextFieldMolecule } from './TextFieldMolecule.svelte';
	import FormDataMolecule from '../zz-meta-components/FormDataPreview/FormDataMolecule.svelte';

	const { label, placeholder }: PropsForTextFieldMolecule = $props();

	const form = createForm(() => ({
		defaultValues: {
			firstName: ''
		},
		onSubmit: async ({ value }) => {
			alert(JSON.stringify(value, null, 2));
		}
	}));

	const formValues = $derived(useStore(form.store, (s) => s.values));
</script>

<form
	id="form"
	onsubmit={(e) => {
		e.preventDefault();
		form.handleSubmit();
	}}
>
	<form.Field name="firstName">
		{#snippet children(field)}
			<FormDataMolecule formValues={formValues.current}>
				<TextFieldMolecule {label} {placeholder} {field} />
			</FormDataMolecule>
		{/snippet}
	</form.Field>
</form>
