// example-site/svelte/src/components/01-atoms/BgImageContainerAtom.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	export interface PropsForBgImageContainerAtom {
		imgSrc?: string;
		altText?: string;
		className?: string;
		innerClassName?: string;
		tintColor?: string;
		tintPercent?: number;
		children?: Snippet;
	}

	const {
		children,
		imgSrc,
		altText = '',
		className = '',
		tintColor = 'white',
		tintPercent = 70,
		innerClassName = ''
	}: PropsForBgImageContainerAtom = $props();
</script>

<div class={`BgImageContainerAtom relative ${className}`}>
	<img src={imgSrc} alt={altText} class="absolute top-0 left-0 h-full w-full object-cover" />
	<div
		class="absolute top-0 left-0 h-full w-full"
		style:background-color={tintColor}
		style:opacity={`${tintPercent}%`}
	></div>
	<div class={`relative z-10 grid ${innerClassName}`}>
		{@render children?.()}
	</div>
</div>

// example-site/vue/app/components/01-atoms/BgImageContainerAtom.vue
<script setup lang="ts">
export interface PropsForBgImageContainerAtom {
	className?: string
	imgSrc: string
	altText: string
	tintColor?: string
	tintPercent?: number
	innerClassName?: string
}

const {
	className,
	imgSrc,
	altText,
	tintColor = 'white',
	tintPercent = 70,
	innerClassName,
} = defineProps<PropsForBgImageContainerAtom>()
</script>

<template>
	<div class="BgImageContainerAtom relative" :class="className">
		<img
			:src="imgSrc"
			:alt="altText"
			class="absolute top-0 left-0 h-full w-full object-cover"
		/>
		<div
			class="absolute top-0 left-0 h-full w-full"
			:style="{
				backgroundColor: tintColor,
				opacity: tintPercent / 100,
			}"
		></div>
		<div class="relative z-10 grid" :class="innerClassName">
			<slot />
		</div>
	</div>
</template>
