// example-site/src/components/listings/compact/CompactListingOrganism.tsx
import {
	CompactListingMolecule,
	type PropsForCompactListingMolecule,
} from './CompactListingMolecule'

export interface PropsForCompactListingOrganism {
	items: Array<PropsForCompactListingMolecule>
}

export function CompactListingOrganism({
	items,
}: PropsForCompactListingOrganism) {
	return (
		<ul className="grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-4">
			{items.map((item) => (
				<li key={item.title}>
					<CompactListingMolecule {...item} />
				</li>
			))}
		</ul>
	)
}

// example-site/svelte/src/components/listings/compact/CompactListingOrganism.svelte
<script lang="ts">
	import type { PropsForCompactListingMolecule } from './CompactListingMolecule.svelte';
	import CompactListingMolecule from './CompactListingMolecule.svelte';

	export interface PropsForCompactListingOrganism {
		items: Array<PropsForCompactListingMolecule>;
	}

	const { items }: PropsForCompactListingOrganism = $props();
</script>

<ul class="CompactListingOrganism gap-4">
	{#each items as item (item.title)}
		<li>
			<CompactListingMolecule {...item} />
		</li>
	{/each}
</ul>

<style>
	.CompactListingOrganism {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
	}
</style>
