// example-site/vue/app/components/forms/ContactFormOrganism/ContactFormOrganism.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Field, Form, getAllErrors, type FormStore } from '@formisch/vue'
import type {
	ContactFormOutputData,
	ContactFormSchemaType,
} from 'example-site-shared/data'
import ButtonAtom from '../../01-atoms/ButtonAtom.vue'
import TextFieldMolecule from '../TextFieldMolecule/TextFieldMolecule.vue'
import TextAreaMolecule from '../TextAreaMolecule/TextAreaMolecule.vue'
import ErrorBlockOrganism from '../ErrorMessages/ErrorBlockOrganism.vue'

export interface PropsForContactFormOrganism {
	form: FormStore<ContactFormSchemaType>
	onSubmit?: (output: ContactFormOutputData) => void
}

const { form, onSubmit } = defineProps<PropsForContactFormOrganism>()

const errors = computed(() => getAllErrors(form))
</script>

<template>
	<div class="grid gap-4">
		<ErrorBlockOrganism :errors="errors" />

		<Form
			id="form"
			class="grid gap-4"
			:of="form"
			@submit="(output) => onSubmit?.(output)"
		>
			<Field :of="form" :path="['name']" v-slot="field">
				<TextFieldMolecule
					label="Name"
					placeholder="Your name"
					:field="field"
				/>
			</Field>

			<Field :of="form" :path="['email']" v-slot="field">
				<TextFieldMolecule
					label="Email"
					placeholder="example@email.com"
					:field="field"
				/>
			</Field>

			<Field :of="form" :path="['message']" v-slot="field">
				<TextAreaMolecule
					label="Message"
					placeholder="Type your message here..."
					:field="field"
				/>
			</Field>

			<div class="flex justify-end">
				<ButtonAtom type="submit">Send</ButtonAtom>
			</div>
		</Form>
	</div>
</template>

// example-site/react/src/components/forms/ContactFormOrganism/ContactFormOrganism.tsx
import { Field, Form, getAllErrors, useSignals } from '@formisch/react'
import { TextFieldMolecule } from '../TextFieldMolecule/TextFieldMolecule'
import { TextAreaMolecule } from '../TextAreaMolecule/TextAreaMolecule'
import { ButtonAtom } from '../../01-atoms/ButtonAtom'
import type { FormStore, SubmitHandler } from '@formisch/react'
import type { ContactFormSchemaType } from 'example-site-shared/data'
import { ErrorBlockOrganism } from '../ErrorMessages/ErrorBlockOrganism'

export interface PropsForContactFormOrganism {
	form: FormStore<ContactFormSchemaType>
	onSubmit: SubmitHandler<ContactFormSchemaType>
}

export function ContactFormOrganism({
	form,
	onSubmit,
}: PropsForContactFormOrganism) {
	useSignals()
	const errors = getAllErrors(form)
	return (
		<div className="grid gap-4">
			<ErrorBlockOrganism errors={errors} />
			<Form
				className="ContactFormOrganism grid gap-4"
				of={form}
				onSubmit={onSubmit}
			>
				<Field of={form} path={['name']}>
					{(field) => (
						<TextFieldMolecule
							label="Name"
							placeholder="Your name"
							field={field}
						/>
					)}
				</Field>

				<Field of={form} path={['email']}>
					{(field) => (
						<TextFieldMolecule
							label="Email"
							placeholder="example@email.com"
							field={field}
						/>
					)}
				</Field>

				<Field of={form} path={['message']}>
					{(field) => (
						<TextAreaMolecule
							label="Message"
							placeholder="Type your message here..."
							field={field}
						/>
					)}
				</Field>

				<div className="flex justify-end">
					<ButtonAtom type="submit">Send</ButtonAtom>
				</div>
			</Form>
		</div>
	)
}
