// example-site/svelte/src/components/forms/TextAreaMolecule/TextAreaMolecule.decorator.svelte
<script lang="ts">
	import TextAreaMolecule, { type PropsForTextAreaMolecule } from './TextAreaMolecule.svelte';
	import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.svelte';
	import { createForm, Form, Field, type ValidationMode } from '@formisch/svelte';
	import { defaultMessageOnlyValues, messageOnlySchema } from 'example-site-shared/data';

	interface DecoratorProps extends Omit<PropsForTextAreaMolecule, 'field'> {
		validate?: ValidationMode;
	}

	const { label, placeholder, validate }: DecoratorProps = $props();

	const form = $derived(
		createForm({
			schema: messageOnlySchema,
			initialInput: defaultMessageOnlyValues,
			validate
		})
	);
</script>

<Form
	of={form}
	id="form"
	onsubmit={(outputData, e) => {
		e.preventDefault();
		alert(JSON.stringify(outputData, null, 2));
	}}
>
	<Field of={form} path={['message']}>
		{#snippet children(field)}
			<FormDataMolecule {form}>
				<TextAreaMolecule {label} {placeholder} {field} />
			</FormDataMolecule>
		{/snippet}
	</Field>
</Form>

// example-site/vue/components/forms/TextAreaMolecule/TextAreaMolecule.decorator.vue
<script setup lang="ts">
import { Field, Form, useForm, type ValidationMode } from '@formisch/vue'
import {
	defaultMessageOnlyValues,
	messageOnlySchema,
	type MessageOnlyOutputData,
} from 'example-site-shared/data'
import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.vue'
import TextAreaMolecule, {
	type PropsForTextAreaMolecule,
} from './TextAreaMolecule.vue'

interface DecoratorProps extends Omit<PropsForTextAreaMolecule, 'field'> {
	validate?: ValidationMode
}

const { label, placeholder, validate } = defineProps<DecoratorProps>()

const form = useForm({
	schema: messageOnlySchema,
	initialInput: defaultMessageOnlyValues,
	validate,
})

function onSubmit(output: MessageOnlyOutputData) {
	alert(JSON.stringify(output, null, 2))
}
</script>

<template>
	<Form id="form" :of="form" @submit="onSubmit">
		<Field :of="form" :path="['message']" v-slot="field">
			<FormDataMolecule :form="form">
				<TextAreaMolecule
					:label="label"
					:placeholder="placeholder"
					:field="field"
				/>
			</FormDataMolecule>
		</Field>
	</Form>
</template>
