// example-site/svelte/src/components/forms/ErrorMessages/ErrorBlockOrganism.svelte
<script lang="ts">
	import { H, Level } from 'svelte-headings';
	import ErrorListMolecule from './ErrorListMolecule.svelte';

	export interface PropsForErrorBlockOrganism {
		errors: Array<string | Error>;
	}

	const { errors }: PropsForErrorBlockOrganism = $props();
</script>

<div role="alert" class="ErrorBlockOrganism">
	{#if errors.length > 0}
		<Level class="rounded-xl bg-red-100 px-4 pt-2">
			<H class="border-b-2 border-red-800 pb-1 text-2xl font-bold">
				Please resolve the following errors
			</H>
			<div class="pt-3 pb-4">
				<ErrorListMolecule {errors} />
			</div>
		</Level>
	{/if}
</div>

// example-site/src/components/forms/ErrorMessages/ErrorBlockOrganism.tsx
import { clsx } from 'clsx'
import { ErrorListMolecule } from './ErrorListMolecule'

export interface PropsForErrorBlockOrganism {
  errors: Array<string | Error>
}

export function ErrorBlockOrganism({ errors }: PropsForErrorBlockOrganism) {
  return (
    <div
      role="alert"
      className={clsx({
        absolute: errors.length === 0,
      })}
    >
      {errors.length > 0 && (
        <div>
          <h2>Please resolve the following errors</h2>
          <ErrorListMolecule errors={errors} />
        </div>
      )}
    </div>
  )
}
