// example-site/vue/app/components/forms/ErrorMessages/ErrorMessageAtom.vue
<script setup lang="ts">
export interface PropsForErrorMessageAtom {
	error: string | Error
}

const { error } = defineProps<PropsForErrorMessageAtom>()
</script>

<template>
	<p class="leading-none font-bold text-red-900">
		{{ typeof error === 'string' ? error : error.message }}
	</p>
</template>

// example-site/src/components/forms/ErrorMessages/ErrorMessageAtom.tsx
export interface PropsForErrorMessageAtom {
  error: string | Error
}

export function ErrorMessageAtom({ error }: PropsForErrorMessageAtom) {
  return (
    <p
      key={typeof error === 'string' ? error : error.message}
      className="text-red-500 mt-1 font-bold"
    >
      {typeof error === 'string' ? error : error.message}
    </p>
  )
}
