// example-site/svelte/src/components/03-organisms/HeroBlockOrganism.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import BgImageContainerAtom from '../01-atoms/BgImageContainerAtom.svelte';
	import ScreenPaddingAtom from '../01-atoms/ScreenPaddingAtom.svelte';
	import { H } from 'svelte-headings';

	export interface PropsForHeroBlockOrganism {
		title: string | Snippet;
		imgSrc?: string;
		tintPercent?: number;
		tintColor?: string;
		altText?: string;
		children?: Snippet;
	}

	const { children, title, imgSrc, tintPercent, tintColor, altText }: PropsForHeroBlockOrganism =
		$props();
</script>

<BgImageContainerAtom
	className="HeroBlockOrganism text-center w-full min-h-100 grid place-items-center border-b-2 border-teal-900"
	{imgSrc}
	{altText}
	{tintColor}
	{tintPercent}
>
	<ScreenPaddingAtom padVertical>
		<!-- No need for a Level wrapper here because the Wrapper is in the SiteFrame component -->
		<H class="text-4xl font-bold">{title}</H>
		{@render children?.()}
	</ScreenPaddingAtom>
</BgImageContainerAtom>

// example-site/vue/components/03-organisms/HeroBlockOrganism.vue
<script setup lang="ts">
import BgImageContainerAtom from '../01-atoms/BgImageContainerAtom.vue'
import ScreenPaddingAtom from '../01-atoms/ScreenPaddingAtom.vue'

export interface PropsForHeroBlockOrganism {
	title: string
	imgSrc?: string
	tintPercent?: number
	tintColor?: string
	altText?: string
}

const {
	title,
	imgSrc = '',
	tintPercent,
	tintColor,
	altText = '',
} = defineProps<PropsForHeroBlockOrganism>()
</script>

<template>
	<BgImageContainerAtom
		className="HeroBlockOrganism text-center w-full min-h-100 grid place-items-center border-b-2 border-teal-900"
		:imgSrc="imgSrc"
		:altText="altText"
		:tintColor="tintColor"
		:tintPercent="tintPercent"
	>
		<ScreenPaddingAtom padVertical>
			<!-- No need for a Level wrapper here because the Wrapper is in the SiteFrame component -->
			<h1 class="text-4xl font-bold">{{ title }}</h1>
			<slot />
		</ScreenPaddingAtom>
	</BgImageContainerAtom>
</template>
