// example-site/solid/src/components/forms/TextAreaMolecule/TextAreaMolecule.tsx
import { createUniqueId, Show } from 'solid-js'
import { ErrorListMolecule } from '../ErrorMessages/ErrorListMolecule'
import type { FormSchema, RequiredPath } from '@formisch/solid'
import type { WithField } from '../FormTypes'

export interface PropsForTextAreaMolecule {
	label: string
	placeholder?: string
}

export type FieldPropsForTextAreaMolecule<
	TSchema extends FormSchema,
	TPath extends RequiredPath,
> = PropsForTextAreaMolecule & WithField<TSchema, TPath>

export function TextAreaMolecule<
	TSchema extends FormSchema,
	TPath extends RequiredPath,
>(props: FieldPropsForTextAreaMolecule<TSchema, TPath>) {
	// Built from a counter rather than the label, so that two fields sharing a
	// label — which the stories for this component do — still get an id each.
	const id = createUniqueId()
	// Written as a function so that each use below reads the errors afresh.
	// Checking the field finishes just after the first draw, and Solid only
	// re-draws the parts of the page that read a value from inside the markup.
	const checkHasErrors = () => (props.field.errors?.length ?? 0) > 0

	return (
		<div>
			<label for={id} class="block mb-1 w-full">
				<span class="font-bold text-xl">{props.label}</span>
				<div class="grid grid-cols-[minmax(0,1fr)]">
					<textarea
						{...props.field.props}
						id={id}
						placeholder={props.placeholder}
						class={`col-start-1 row-start-1 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 ${checkHasErrors() ? 'placeholder-red-900/60' : ''}`}
					/>
					<span class="col-start-1 row-start-1 px-4 py-2 pointer-events-none whitespace-pre-wrap invisible">
						{String(props.field.input ?? '')}{' '}
					</span>
				</div>
			</label>
			<Show when={checkHasErrors()}>
				<ErrorListMolecule errors={props.field.errors ?? []} />
			</Show>
		</div>
	)
}

// example-site/preact/src/components/forms/TextAreaMolecule/TextAreaMolecule.tsx
import { useId } from 'preact/hooks'
import { ErrorListMolecule } from '../ErrorMessages/ErrorListMolecule'
import type { FormSchema, RequiredPath } from '@formisch/preact'
import type { WithField } from '../FormTypes'

export interface PropsForTextAreaMolecule {
	label: string
	placeholder?: string
}

export type FieldPropsForTextAreaMolecule<
	TSchema extends FormSchema,
	TPath extends RequiredPath,
> = PropsForTextAreaMolecule & WithField<TSchema, TPath>

export function TextAreaMolecule<
	TSchema extends FormSchema,
	TPath extends RequiredPath,
>({
	field,
	label,
	placeholder,
}: FieldPropsForTextAreaMolecule<TSchema, TPath>) {
	// Built from a counter rather than the label, so that two fields sharing a
	// label — which the stories for this component do — still get an id each.
	const id = useId()
	// Read through `.value` because Formisch's Preact build hands a field's
	// errors and its typed-in text over as signals — small boxes holding a
	// value that tell the page to redraw when it changes.
	const errors = field.errors.value
	const hasErrors = (errors?.length ?? 0) > 0

	return (
		<div>
			<label for={id} class="block mb-1 w-full">
				<span class="font-bold text-xl">{label}</span>
				<div class="grid grid-cols-[minmax(0,1fr)]">
					<textarea
						{...field.props}
						id={id}
						placeholder={placeholder}
						class={`col-start-1 row-start-1 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 ${hasErrors ? 'placeholder-red-900/60' : ''}`}
					/>
					{/* An invisible copy of what has been typed, sharing the same grid
					cell as the box above. It is what gives the cell its height, so the
					box grows as the message does instead of gaining a scrollbar. The
					trailing space keeps a newline at the end from collapsing. */}
					<span class="col-start-1 row-start-1 px-4 py-2 pointer-events-none whitespace-pre-wrap invisible">
						{String(field.input.value ?? '')}{' '}
					</span>
				</div>
			</label>
			{hasErrors && <ErrorListMolecule errors={errors} />}
		</div>
	)
}
