// example-site/angular/src/components/01-atoms/BgImageContainerAtom.component.ts
import { Component, input } from '@angular/core';

@Component({
	selector: 'bg-image-container-atom',
	template: `
		<div [class]="'BgImageContainerAtom relative ' + class()">
			<img
				[src]="imgSrc()"
				[alt]="altText()"
				class="absolute top-0 left-0 h-full w-full object-cover"
			/>
			<div
				class="absolute inset-0"
				[style]="
					['background-color: ' + tintColor(), 'opacity: ' + tintPercent() / 100].join('; ')
				"
			></div>
			<div [class]="'relative z-10 grid' + innerClass()">
				<ng-content />
			</div>
		</div>
	`,
	standalone: true,
	imports: [],
})
export class BgImageContainerAtomComponent {
	class = input<string>('');
	innerClass = input<string>('');
	imgSrc = input<string>();
	altText = input<string>('');
	tintColor = input<string>('white');
	tintPercent = input<number>(70);
}

<div
	class="BgImageContainerAtom relative grid grid-cols-1 grid-rows-1"
	[class]="className()"
>
	<img
		[src]="imgSrc()"
		[alt]="altText()"
		class="object-cover h-full w-full absolute top-0 left-0 col-start-1 row-start-1"
	/>
	<div
		class="h-full w-full absolute top-0 left-0 col-start-1 row-start-1"
		[ngStyle]="{
			'background-color': tintColor(),
			opacity: tintPercent() / 100,
		}"
	></div>
	<div
		class="relative z-10 text-black text-2xl font-bold p-4 col-start-1 row-start-1 grid place-items-center"
		[class]="innerClassName()"
	>
		<ng-content />
	</div>
</div>

// example-site/svelte/src/components/01-atoms/BgImageContainerAtom.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	export interface PropsForBgImageContainerAtom {
		imgSrc?: string;
		altText?: string;
		className?: string;
		innerClassName?: string;
		tintColor?: string;
		tintPercent?: number;
		children?: Snippet;
	}

	const {
		children,
		imgSrc,
		altText = '',
		className = '',
		tintColor = 'white',
		tintPercent = 70,
		innerClassName = ''
	}: PropsForBgImageContainerAtom = $props();
</script>

<div class={`BgImageContainerAtom relative ${className}`}>
	<img src={imgSrc} alt={altText} class="absolute top-0 left-0 h-full w-full object-cover" />
	<div
		class="absolute top-0 left-0 h-full w-full"
		style:background-color={tintColor}
		style:opacity={`${tintPercent}%`}
	></div>
	<div class={`relative z-10 grid ${innerClassName}`}>
		{@render children?.()}
	</div>
</div>
