// example-site/vue/components/01-atoms/ContentRestraintAtom.vue
<script setup lang="ts">
import ScreenPaddingAtom from './ScreenPaddingAtom.vue'

export interface PropsForContentRestraintAtom {
	padVertical?: boolean
}

const { padVertical } = defineProps<PropsForContentRestraintAtom>()
</script>

<template>
	<ScreenPaddingAtom :pad-vertical="padVertical">
		<div
			class="ContentRestraintAtom grid grid-cols-[1fr_minmax(auto,800px)_1fr]"
		>
			<div class="width-full col-start-2 h-full">
				<slot />
			</div>
		</div>
	</ScreenPaddingAtom>
</template>

// example-site/svelte/src/components/01-atoms/ContentRestraintAtom.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import ScreenPaddingAtom from './ScreenPaddingAtom.svelte';

	export interface PropsForContentRestraintAtom {
		children?: Snippet;
		padVertical?: boolean;
	}

	const { children, padVertical }: PropsForContentRestraintAtom = $props();
</script>

<ScreenPaddingAtom {padVertical}>
	<div class="ContentRestraintAtom grid grid-cols-[1fr_minmax(auto,800px)_1fr]">
		<div class="width-full col-start-2 h-full">{@render children?.()}</div>
	</div>
</ScreenPaddingAtom>
