// example-site/vue/app/components/02-molecules/MainNavMolecule.vue
<script setup lang="ts">
import { useActiveNavItem } from '../../composables/useActiveNavItem'

export interface PropsForMainNavMolecule {}

const {} = defineProps<PropsForMainNavMolecule>()

const activeNavItem = useActiveNavItem()
</script>

<template>
	<nav class="MainNavMolecule flex flex-row gap-4 font-bold">
		<NuxtLink to="/" :class="{ underline: activeNavItem === 'home' }"
			>Home</NuxtLink
		>
		<NuxtLink
			to="/categories"
			:class="{ underline: activeNavItem === 'categories' }"
			>Food categories</NuxtLink
		>
		<NuxtLink
			to="/contact"
			:class="{ underline: activeNavItem === 'contact' }"
			>Contact us</NuxtLink
		>
	</nav>
</template>

// example-site/src/components/02-molecules/MainNavMolecule.tsx
import { Link } from '@tanstack/react-router'

export interface PropsForMainNavMolecule {}

export function MainNavMolecule({}: PropsForMainNavMolecule) {
	return (
		<nav className="flex flex-row">
			<div className="px-2 font-bold">
				<Link to="/">Home</Link>
			</div>

			<div className="px-2 font-bold">
				<Link to="/categories">Food categories</Link>
			</div>

			<div className="px-2 font-bold">
				<Link to="/contact">Contact us</Link>
			</div>
		</nav>
	)
}
