// example-site/svelte/src/components/forms/TextFieldMolecule/TextFieldMolecule.decorator.svelte
<script lang="ts">
	import TextFieldMolecule, { type PropsForTextFieldMolecule } from './TextFieldMolecule.svelte';
	import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.svelte';
	import { createForm, Form, Field, type ValidationMode } from '@formisch/svelte';
	import { defaultFirstNameOnlyValues, firstNameOnlySchema } from 'example-site-shared/data';

	interface DecoratorProps extends Omit<PropsForTextFieldMolecule, 'field'> {
		validate?: ValidationMode;
	}

	const { label, placeholder, validate }: DecoratorProps = $props();

	const form = $derived(
		createForm({
			schema: firstNameOnlySchema,
			initialInput: defaultFirstNameOnlyValues,
			validate
		})
	);
</script>

<Form
	of={form}
	id="form"
	onsubmit={(outputData, e) => {
		e.preventDefault();
		alert(JSON.stringify(outputData, null, 2));
	}}
>
	<Field of={form} path={['firstName']}>
		{#snippet children(field)}
			<FormDataMolecule {form}>
				<TextFieldMolecule {label} {placeholder} {field} />
			</FormDataMolecule>
		{/snippet}
	</Field>
</Form>

// example-site/vue/components/forms/TextFieldMolecule/TextFieldMolecule.decorator.vue
<script setup lang="ts">
import { Field, Form, useForm, type ValidationMode } from '@formisch/vue'
import {
	defaultFirstNameOnlyValues,
	firstNameOnlySchema,
	type FirstNameOnlyOutputData,
} from 'example-site-shared/data'
import FormDataMolecule from '../../zz-meta-components/FormDataPreview/FormDataMolecule.vue'
import TextFieldMolecule, {
	type PropsForTextFieldMolecule,
} from './TextFieldMolecule.vue'

interface DecoratorProps extends Omit<PropsForTextFieldMolecule, 'field'> {
	validate?: ValidationMode
}

const { label, placeholder, validate } = defineProps<DecoratorProps>()

const form = useForm({
	schema: firstNameOnlySchema,
	initialInput: defaultFirstNameOnlyValues,
	validate,
})

function onSubmit(output: FirstNameOnlyOutputData) {
	alert(JSON.stringify(output, null, 2))
}
</script>

<template>
	<Form id="form" :of="form" @submit="onSubmit">
		<Field :of="form" :path="['firstName']" v-slot="field">
			<FormDataMolecule :form="form">
				<TextFieldMolecule
					:label="label"
					:placeholder="placeholder"
					:field="field"
				/>
			</FormDataMolecule>
		</Field>
	</Form>
</template>
