// example-site/vue/app/components/forms/ContactFormOrganism/ContactFormOrganism.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Field, Form, getAllErrors, type FormStore } from '@formisch/vue'
import type {
	ContactFormOutputData,
	ContactFormSchemaType,
} from 'example-site-shared/data'
import ButtonAtom from '../../01-atoms/ButtonAtom.vue'
import TextFieldMolecule from '../TextFieldMolecule/TextFieldMolecule.vue'
import TextAreaMolecule from '../TextAreaMolecule/TextAreaMolecule.vue'
import ErrorBlockOrganism from '../ErrorMessages/ErrorBlockOrganism.vue'

export interface PropsForContactFormOrganism {
	form: FormStore<ContactFormSchemaType>
	onSubmit?: (output: ContactFormOutputData) => void
}

const { form, onSubmit } = defineProps<PropsForContactFormOrganism>()

const errors = computed(() => getAllErrors(form))
</script>

<template>
	<div class="grid gap-4">
		<ErrorBlockOrganism :errors="errors" />

		<Form
			id="form"
			class="grid gap-4"
			:of="form"
			@submit="(output) => onSubmit?.(output)"
		>
			<Field :of="form" :path="['name']" v-slot="field">
				<TextFieldMolecule
					label="Name"
					placeholder="Your name"
					:field="field"
				/>
			</Field>

			<Field :of="form" :path="['email']" v-slot="field">
				<TextFieldMolecule
					label="Email"
					placeholder="example@email.com"
					:field="field"
				/>
			</Field>

			<Field :of="form" :path="['message']" v-slot="field">
				<TextAreaMolecule
					label="Message"
					placeholder="Type your message here..."
					:field="field"
				/>
			</Field>

			<div class="flex justify-end">
				<ButtonAtom type="submit">Send</ButtonAtom>
			</div>
		</Form>
	</div>
</template>

// example-site/svelte/src/components/forms/ContactFormOrganism/ContactFormOrganism.svelte
<script lang="ts">
	import { Form, Field, type FormStore, getAllErrors } from '@formisch/svelte';
	import type { ContactFormOutputData, ContactFormSchemaType } from 'example-site-shared/data';
	import TextAreaMolecule from '../TextAreaMolecule/TextAreaMolecule.svelte';
	import ButtonAtom from '../../01-atoms/ButtonAtom.svelte';
	import TextFieldMolecule from '../TextFieldMolecule/TextFieldMolecule.svelte';
	import ErrorBlockOrganism from '../ErrorMessages/ErrorBlockOrganism.svelte';

	export interface PropsForContactFormOrganism {
		form: FormStore<ContactFormSchemaType>;
		onSubmit?: (output: ContactFormOutputData) => void;
	}

	let { form, onSubmit }: PropsForContactFormOrganism = $props();

	const errors = $derived(getAllErrors(form));
</script>

<div class="grid gap-4">
	<ErrorBlockOrganism {errors} />

	<Form
		of={form}
		id="form"
		class="grid gap-4"
		onsubmit={(output, e) => {
			e.preventDefault();
			onSubmit?.(output);
		}}
	>
		<Field of={form} path={['name']}>
			{#snippet children(field)}
				<TextFieldMolecule label="Name" placeholder="Your name" {field} />
			{/snippet}
		</Field>

		<Field of={form} path={['email']}>
			{#snippet children(field)}
				<TextFieldMolecule label="Email" placeholder="example@email.com" {field} />
			{/snippet}
		</Field>

		<Field of={form} path={['message']}>
			{#snippet children(field)}
				<TextAreaMolecule label="Message" placeholder="Type your message here..." {field} />
			{/snippet}
		</Field>

		<div class="flex justify-end">
			<ButtonAtom type="submit">Send</ButtonAtom>
		</div>
	</Form>
</div>
