// example-site/vue/components/forms/ErrorMessages/ErrorListMolecule.vue
<script setup lang="ts">
import type { FormErrors } from '../FormTypes'
import ErrorMessageAtom from './ErrorMessageAtom.vue'

export interface PropsForErrorListMolecule {
	errors: FormErrors
}

const { errors } = defineProps<PropsForErrorListMolecule>()
</script>

<template>
	<ul
		v-if="errors && errors.length > 0"
		class="ErrorListMolecule grid gap-1 pl-6"
	>
		<li
			v-for="err in errors"
			:key="err instanceof Error ? err.message : err"
			class="list-outside list-disc"
		>
			<ErrorMessageAtom :error="err" />
		</li>
	</ul>
</template>

// example-site/svelte/src/components/forms/ErrorMessages/ErrorListMolecule.svelte
<script lang="ts">
	import ErrorMessageAtom from './ErrorMessageAtom.svelte';
	import type { FormErrors } from '../FormTypes';

	export interface PropsForErrorListMolecule {
		errors: FormErrors;
	}

	const { errors }: PropsForErrorListMolecule = $props();
</script>

{#if errors && errors.length > 0}
	<ul class="ErrorListMolecule grid gap-1 pl-6">
		{#each errors as err}
			<li class="list-outside list-disc">
				<ErrorMessageAtom error={err} />
			</li>
		{/each}
	</ul>
{/if}
