// example-site/react/src/components/forms/ErrorMessages/ErrorBlockOrganism.tsx
import { ErrorListMolecule } from './ErrorListMolecule'
import type { FormErrors } from '../FormTypes'

export interface PropsForErrorBlockOrganism {
	errors: FormErrors
}

export function ErrorBlockOrganism({ errors }: PropsForErrorBlockOrganism) {
	if (!errors?.length) return null
	return (
		<div role="alert" className="bg-red-100 px-4 pt-2 rounded-xl">
			<h2 className="text-2xl font-bold border-b-2 border-red-800 pb-1">
				Please resolve the following errors
			</h2>
			<div className="pt-3 pb-4">
				<ErrorListMolecule errors={errors} />
			</div>
		</div>
	)
}

// example-site/svelte/src/components/forms/ErrorMessages/ErrorBlockOrganism.svelte
<script lang="ts">
	import { H, Level } from 'svelte-headings';
	import ErrorListMolecule from './ErrorListMolecule.svelte';
	import type { FormErrors } from '../FormTypes';

	export interface PropsForErrorBlockOrganism {
		errors: FormErrors;
	}

	const { errors }: PropsForErrorBlockOrganism = $props();
</script>

{#if errors && errors.length > 0}
	<div role="alert" class="ErrorBlockOrganism">
		<Level class="rounded-xl bg-red-100 px-4 pt-2">
			<H class="border-b-2 border-red-800 pb-1 text-2xl font-bold">
				Please resolve the following errors
			</H>
			<div class="pt-3 pb-4">
				<ErrorListMolecule {errors} />
			</div>
		</Level>
	</div>
{/if}
