// example-site/solid/src/routes/categories/[category].tsx
import { Title } from '@solidjs/meta'
import {
	createAsync,
	query,
	useParams,
	type RouteDefinition,
} from '@solidjs/router'
import { fetchMealsByCategory } from 'example-site-shared/utils'
import { CardListTemplate } from '../../components/04-templates/CardListTemplate'

const getMealsByCategory = query(fetchMealsByCategory, 'mealsByCategory')

export const route = {
	// `params` is typed as possibly missing because it is shared by every
	// route, so there is nothing to fetch ahead of time without a category.
	preload: ({ params }) => {
		if (!params.category) return
		return getMealsByCategory(decodeURIComponent(params.category))
	},
} satisfies RouteDefinition

export default function CategoryMeals() {
	const params = useParams<{ category: string }>()
	const categoryName = () => decodeURIComponent(params.category)
	const meals = createAsync(() => getMealsByCategory(categoryName()))

	return (
		<>
			<Title>{categoryName()} Meals | The Meal Place</Title>
			<CardListTemplate
				title={`${categoryName()} meals`}
				introText={`Explore the delicious ${categoryName()} meals!`}
				cardList={meals()?.map((meal) => ({
					title: meal.name,
					description: meal.area,
					imgSrc: meal.image,
					href: '/meal/$mealId',
					hrefParams: { mealId: meal.id },
				}))}
			/>
		</>
	)
}

// example-site/vue/app/pages/categories/[category].vue
<script setup lang="ts">
import { computed } from 'vue'
import CardListTemplate from '../../../components/04-templates/CardListTemplate.vue'
import type { PropsForCardMolecule } from '../../../components/listings/card/CardMolecule.vue'
import { fetchMealsByCategory } from 'example-site-shared/utils/mealDbApiUtils'

const route = useRoute()
const category = computed(() => String(route.params.category))

const { data: mealList } = await useAsyncData(
	`category-${category.value}`,
	() => fetchMealsByCategory(category.value),
	{ watch: [category] },
)

const cardList = computed<Array<PropsForCardMolecule>>(() =>
	(mealList.value ?? []).map((meal) => ({
		title: meal.name,
		description: meal.area,
		imgSrc: meal.image,
		href: '/meal/$mealId',
		hrefParams: { mealId: meal.id },
	})),
)

useHead({ title: () => `${category.value} Meals` })
useSeoMeta({
	description:
		'Explore the delicious meals in this category! Click on any meal to discover its recipe, ingredients, and cooking instructions.',
})
</script>

<template>
	<CardListTemplate
		title="Meals in this category"
		introText="Explore the delicious meals in this category! Click on any meal to discover its recipe, ingredients, and cooking instructions."
		:cardList="cardList"
	/>
</template>
