// example-site/solid/src/routes/categories/index.tsx
import { Title } from '@solidjs/meta'
import { createAsync, query, type RouteDefinition } from '@solidjs/router'
import { fetchCategories } from 'example-site-shared/utils'
import { CardListTemplate } from '../../components/04-templates/CardListTemplate'

const getCategories = query(fetchCategories, 'categories')

export const route = {
	preload: () => getCategories(),
} satisfies RouteDefinition

export default function Categories() {
	const categories = createAsync(() => getCategories())

	return (
		<>
			<Title>Meal Categories | The Meal Place</Title>
			<CardListTemplate
				title="Food Categories"
				introText="Explore what delicious types of food await you!"
				cardList={categories()?.map((category) => ({
					title: category.strCategory,
					description: category.strCategoryDescription,
					imgSrc: category.strCategoryThumb,
					href: '/categories/$category',
					hrefParams: { category: category.strCategory },
				}))}
			/>
		</>
	)
}

// example-site/vue/app/pages/categories/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import CardListTemplate from '../../components/04-templates/CardListTemplate.vue'
import type { PropsForCardMolecule } from '../../components/listings/card/CardMolecule.vue'
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils'

const introText =
	'Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration.'

const { data: categories } = await useAsyncData('categories', () =>
	fetchCategories(),
)

const cardList = computed<Array<PropsForCardMolecule>>(() =>
	(categories.value ?? []).map((category) => ({
		title: category.strCategory,
		description: category.strCategoryDescription,
		imgSrc: category.strCategoryThumb,
		href: '/categories/[category]',
		hrefParams: { category: category.strCategory },
	})),
)

useHead({ title: 'Categories' })
useSeoMeta({ description: introText })
</script>

<template>
	<CardListTemplate
		title="Food Categories"
		:introText="introText"
		:cardList="cardList"
	/>
</template>
