// example-site/src/routes/categories.tsx
import { createFileRoute } from '@tanstack/react-router'
import { fetchCategories } from '../utils/mealDbApiUtils'
import { CardListTemplate } from '../components/04-templates/CardListTemplate'

export const Route = createFileRoute('/categories')({
	component: RouteComponent,
	loader: fetchCategories,
})

function RouteComponent() {
	const categories = Route.useLoaderData()
	return (
		<CardListTemplate
			cardList={categories.map((c) => ({
				title: c.strCategory,
				description: c.strCategoryDescription,
				imgSrc: c.strCategoryThumb,
				href: '/categories/$category',
				hrefParams: { category: c.strCategory },
			}))}
			title="Food Categories"
			introText="Explore what delicious types of food await you!"
		/>
	)
}

// example-site/vue/app/pages/categories/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import CardListTemplate from '../../components/04-templates/CardListTemplate.vue'
import type { PropsForCardMolecule } from '../../components/listings/card/CardMolecule.vue'
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils'

const introText =
	'Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration.'

const { data: categories } = await useAsyncData('categories', () =>
	fetchCategories(),
)

const cardList = computed<Array<PropsForCardMolecule>>(() =>
	(categories.value ?? []).map((category) => ({
		title: category.strCategory,
		description: category.strCategoryDescription,
		imgSrc: category.strCategoryThumb,
		href: '/categories/[category]',
		hrefParams: { category: category.strCategory },
	})),
)

useHead({ title: 'Categories' })
useSeoMeta({ description: introText })
</script>

<template>
	<CardListTemplate
		title="Food Categories"
		:introText="introText"
		:cardList="cardList"
	/>
</template>
