// example-site/svelte/src/components/forms/ContactFormOrganism/ContactFormOrganism.svelte
<script lang="ts">
	import { createForm, useStore } from '@tanstack/svelte-form';
	import { defaultContactFormValues, type ContactFormValues } from 'example-site-shared/data';
	import TextAreaMolecule from '../TextAreaMolecule/TextAreaMolecule.svelte';
	import ButtonAtom from '../../01-atoms/ButtonAtom.svelte';
	import TextFieldMolecule from '../TextFieldMolecule/TextFieldMolecule.svelte';

	export interface PropsForContactFormOrganism {
		onSubmit?: () => void;
		formValues?: ContactFormValues;
	}

	let { onSubmit, formValues = $bindable(defaultContactFormValues) }: PropsForContactFormOrganism =
		$props();

	const form = createForm(() => ({
		defaultValues: defaultContactFormValues,
		onSubmit: onSubmit
	}));

	const values = useStore(form.store, (s) => s.values);

	$effect(() => {
		formValues = values.current;
	});
</script>

<form
	id="form"
	onsubmit={(e) => {
		e.preventDefault();
		form.handleSubmit();
	}}
	class="grid gap-4"
>
	<form.Field name="name">
		{#snippet children(field)}
			<TextFieldMolecule label="Name" placeholder="Your name" {field} />
		{/snippet}
	</form.Field>

	<form.Field name="email">
		{#snippet children(field)}
			<TextFieldMolecule label="Email" placeholder="example@email.com" {field} />
		{/snippet}
	</form.Field>

	<form.Field
		name="message"
		validators={{
			onChange: ({ value }) => {
				if (!value) {
					return 'Message is required';
				} else if (value.length < 10) {
					return 'Message must be at least 10 characters';
				}
			}
		}}
	>
		{#snippet children(field)}
			<TextAreaMolecule label="Message" placeholder="Type your message here..." {field} />
		{/snippet}
	</form.Field>

	<div class="flex justify-end">
		<ButtonAtom type="submit">Send</ButtonAtom>
	</div>
</form>

// example-site/angular/src/components/forms/ContactFormOrganism.component.ts
import { Component, effect, output } from '@angular/core'
import { injectForm, injectStore } from '@tanstack/angular-form'
import { defaultContactFormValues, type ContactFormValues } from 'example-site-shared/data'
import { TextFieldMoleculeComponent } from './TextFieldMolecule/TextFieldMolecule.component'
import { TextAreaMoleculeComponent } from './TextAreaMolecule/TextAreaMolecule.component'
import { ButtonAtomComponent } from '../01-atoms/ButtonAtom.component'

@Component({
	selector: 'contact-form-organism',
	standalone: true,
	imports: [TextFieldMoleculeComponent, TextAreaMoleculeComponent, ButtonAtomComponent],
	template: `
		<form (submit)="handleSubmit($event)" class="ContactFormOrganism grid gap-4">
			<text-field-molecule
				label="Name"
				placeholder="Your name"
				[tanstackField]="form"
				name="name"
				[validators]="nameValidators"
			/>
			<text-field-molecule
				label="Email"
				placeholder="example@email.com"
				[tanstackField]="form"
				name="email"
				[validators]="emailValidators"
			/>
			<text-area-molecule
				label="Message"
				placeholder="Type your message here..."
				[tanstackField]="form"
				name="message"
				[validators]="messageValidators"
			/>
			<div class="flex justify-end">
				<button-atom type="submit">Send</button-atom>
			</div>
		</form>
	`,
})
export class ContactFormOrganismComponent {
	submitted = output<void>()
	valuesChange = output<ContactFormValues>()

	form = injectForm({
		defaultValues: defaultContactFormValues,
		onSubmit: async () => this.submitted.emit(),
	})

	private formValues = injectStore(this.form, (s) => s.values)

	nameValidators = {
		onChange: ({ value }: { value: string }) => (!value ? 'Name is required' : undefined),
	}

	emailValidators = {
		onChange: ({ value }: { value: string }) => {
			if (!value) return 'Email is required'
			if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) return 'Invalid email address'
			return undefined
		},
	}

	messageValidators = {
		onChange: ({ value }: { value: string }) => {
			if (!value) return 'Message is required'
			if (value.length < 10) return 'At least 10 characters are required'
			return undefined
		},
	}

	constructor() {
		effect(() => {
			this.valuesChange.emit(this.formValues() as ContactFormValues)
		})
	}

	handleSubmit(event: SubmitEvent) {
		event.preventDefault()
		this.form.handleSubmit()
	}
}
