// example-site/svelte/src/routes/categories/+page.svelte
<script lang="ts">
	import CardListTemplate from '../../components/04-templates/CardListTemplate.svelte';
	import type { PropsForCardMolecule } from '../../components/listings/card/CardMolecule.svelte';
	import type { PageProps } from './$types';

	const { data }: PageProps = $props();
	const { categories } = $derived(data);
	const cardList: Array<PropsForCardMolecule> = $derived(
		categories.map(
			(c) =>
				({
					title: c.strCategory,
					description: c.strCategoryDescription,
					imgSrc: c.strCategoryThumb,
					href: `/category/${c.strCategory}`
				}) satisfies PropsForCardMolecule
		)
	);
</script>

<svelte:head>
	<title>Categories</title>
	<meta
		name="description"
		content="Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration."
	/>
</svelte:head>

<CardListTemplate
	title="Food Categories"
	introText="Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration."
	{cardList}
/>

// example-site/vue/app/pages/categories.vue
<script setup lang="ts">
import { computed } from 'vue'
import CardListTemplate from '../../components/04-templates/CardListTemplate.vue'
import type { PropsForCardMolecule } from '../../components/listings/card/CardMolecule.vue'
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils'

const introText =
	'Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration.'

const { data: categories } = await useAsyncData('categories', () =>
	fetchCategories(),
)

const cardList = computed<Array<PropsForCardMolecule>>(() =>
	(categories.value ?? []).map((category) => ({
		title: category.strCategory,
		description: category.strCategoryDescription,
		imgSrc: category.strCategoryThumb,
		href: `/category/${category.strCategory}`,
	})),
)

useHead({ title: 'Categories' })
useSeoMeta({ description: introText })
</script>

<template>
	<CardListTemplate
		title="Food Categories"
		:introText="introText"
		:cardList="cardList"
	/>
</template>
