// example-site/angular/src/routes/categories/categories.component.ts
import { Component, signal, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils'
import type { Category } from 'example-site-shared/utils'
import { CardListTemplateComponent } from '../../components/04-templates/CardListTemplate.component'

@Component({
	selector: 'app-categories-route',
	standalone: true,
	imports: [CommonModule, CardListTemplateComponent],
	template: `
		<app-card-list-template
			title="Food categories"
			[cardList]="cardList()"
		/>
	`,
})
export class CategoriesRouteComponent implements OnInit {
	categories = signal<Array<Category>>([])

	cardList = signal<Array<{ title: string; description: string; imgSrc: string; href: string }>>([])

	async ngOnInit() {
		const cats = await fetchCategories()
		this.categories.set(cats)
		this.cardList.set(
			cats.map((c) => ({
				title: c.strCategory,
				description: c.strCategoryDescription,
				imgSrc: c.strCategoryThumb,
				href: `/category/${c.strCategory}`,
			})),
		)
	}
}

// example-site/vue/app/pages/categories.vue
<script setup lang="ts">
import { computed } from 'vue'
import CardListTemplate from '../../components/04-templates/CardListTemplate.vue'
import type { PropsForCardMolecule } from '../../components/listings/card/CardMolecule.vue'
import { fetchCategories } from 'example-site-shared/utils/mealDbApiUtils'

const introText =
	'Explore a variety of food categories at The Meal Place! Discover new recipes, ingredients, and culinary inspiration.'

const { data: categories } = await useAsyncData('categories', () =>
	fetchCategories(),
)

const cardList = computed<Array<PropsForCardMolecule>>(() =>
	(categories.value ?? []).map((category) => ({
		title: category.strCategory,
		description: category.strCategoryDescription,
		imgSrc: category.strCategoryThumb,
		href: `/category/${category.strCategory}`,
	})),
)

useHead({ title: 'Categories' })
useSeoMeta({ description: introText })
</script>

<template>
	<CardListTemplate
		title="Food Categories"
		:introText="introText"
		:cardList="cardList"
	/>
</template>
