// example-site/svelte/src/routes/contact/+page.svelte
<script lang="ts">
	import ContactTemplate from '../../components/04-templates/ContactTemplate.svelte';
</script>

<svelte:head>
	<title>Contact Us</title>
	<meta
		name="description"
		content="Get in touch with us at The Meal Place! We'd love to hear from you, whether you have questions, feedback, or just want to say hello."
	/>
</svelte:head>

<ContactTemplate />

// example-site/vue/app/pages/contact.vue
<script setup lang="ts">
import ContactTemplate from '../../components/04-templates/ContactTemplate.vue'

useHead({ title: 'Contact' })
useSeoMeta({
	description:
		"Get in touch with us at The Meal Place! We'd love to hear from you, whether you have questions, feedback, or just want to say hello.",
})
</script>

<template>
	<ContactTemplate />
</template>
