// example-site/vue/components/listings/compact/CompactListingMolecule.vue
<script setup lang="ts">
export interface PropsForCompactListingMolecule {
	imageSrc: string
	title: string
	description: string
}

const { imageSrc, title, description } =
	defineProps<PropsForCompactListingMolecule>()
</script>

<template>
	<div class="grid grid-cols-[auto_1fr] items-center gap-4">
		<img :src="imageSrc" alt="" class="h-15" />
		<div>
			<h3 class="text-xl leading-none font-bold">{{ title }}</h3>
			<p>{{ description }}</p>
		</div>
	</div>
</template>

// example-site/angular/src/components/listings/compact/CompactListingMolecule.component.ts
import { Component, input } from '@angular/core';
import type { AngularComponentProps } from 'storybook-addon-dependency-previews';

@Component({
	selector: 'compact-listing-molecule',
	template: `
		<div
			[class]="'CompactListingMolecule grid grid-cols-[auto_1fr] items-center gap-4 ' + class()"
		>
			<img [src]="imageSrc()" alt="" class="h-15" />
			<div>
				<h3 class="text-xl leading-none font-bold">{{ title() }}</h3>
				<p>{{ description() }}</p>
			</div>
		</div>
	`,
	standalone: true,
	imports: [],
})
export class CompactListingMoleculeComponent {
	class = input<string>('');
	imageSrc = input<string>('');
	title = input<string>('');
	description = input<string>('');
	href = input<string>('');
}

export type PropsForCompactListingMolecule = AngularComponentProps<
	CompactListingMoleculeComponent,
	'class'
>;

<div class="CompactListingMolecule flex items-center gap-3">
	@if (href()) {
		<a [routerLink]="href()" class="flex items-center gap-3 hover:underline">
			@if (imageSrc()) {
				<img [src]="imageSrc()" [alt]="title()" class="w-12 h-12 object-cover rounded" />
			}
			<div>
				<p class="font-semibold">{{ title() }}</p>
				@if (description()) {
					<p class="text-sm text-gray-600">{{ description() }}</p>
				}
			</div>
		</a>
	} @else {
		@if (imageSrc()) {
			<img [src]="imageSrc()" [alt]="title()" class="w-12 h-12 object-cover rounded" />
		}
		<div>
			<p class="font-semibold">{{ title() }}</p>
			@if (description()) {
				<p class="text-sm text-gray-600">{{ description() }}</p>
			}
		</div>
	}
</div>
