// example-site/vue/app/components/01-atoms/InternalLinkAtom.vue
<script lang="ts">
import type { LinkAddressPropsViaBrackets } from 'example-site-shared/utils'

/**
 * A link to a page inside this site. Pairs with `ExternalLinkAtom`, which is for
 * addresses outside it.
 *
 * `NuxtLink` takes any text at all as its address, so every internal link goes
 * through this one instead: `href` only accepts an address the site actually
 * has, which means a misspelt or wrong-shaped one fails the type check. An
 * address with a marked-out name in it needs that piece supplied as
 * `hrefParams`, and this fills it in, because `NuxtLink` wants a finished
 * address. That part is not checked by the type — a missing piece throws when
 * the link is drawn.
 *
 * The bracket spelling is the one this site writes: `/meal/[mealId]` is the
 * address `pages/meal/[mealId].vue` answers. The two address props and what they
 * mean come from `LinkAddressPropsViaBrackets` rather than being restated here.
 *
 * `activeClass` is the only thing named here beyond the address; a `class` and
 * the link's own content reach the anchor without help.
 */
export interface PropsForInternalLinkAtom extends LinkAddressPropsViaBrackets {
	/**
	 * Class to add while this link points at the page on screen. It also covers a
	 * page sitting under the same parent page file, which is what keeps
	 * `/categories` marked while a category is being read, and the whole reason
	 * `pages/categories.vue` exists.
	 *
	 * vue-router goes by which page files answer the address, never by one
	 * address starting with another's text — so `/` is not marked on `/contact`.
	 *
	 * Left off, vue-router still marks the link, with its own
	 * `router-link-active` name — nothing here styles that, so a link without
	 * this looks the same on its own page as anywhere else.
	 */
	activeClass?: string
}
</script>

<script setup lang="ts">
import { getFullAddressViaBrackets } from 'example-site-shared/utils'

const { href, hrefParams, activeClass } =
	defineProps<PropsForInternalLinkAtom>()
</script>

<template>
	<NuxtLink
		class="InternalLinkAtom"
		:to="getFullAddressViaBrackets({ href, hrefParams })"
		:activeClass="activeClass"
	>
		<slot />
	</NuxtLink>
</template>

// example-site/preact/src/components/01-atoms/InternalLinkAtom.tsx
import type { ComponentChildren } from 'preact'
import { useLocation } from 'preact-iso'
import {
	getFullAddressViaColons,
	type LinkAddressPropsViaColons,
} from 'example-site-shared/utils'

/**
 * A link to a page inside this site. Pairs with `ExternalLinkAtom`, which is
 * for addresses outside it.
 *
 * preact-iso has no link component of its own — it moves between pages by
 * catching clicks on ordinary links — so this is where every internal link
 * goes. It only accepts an address the site actually has, which means a
 * misspelt or wrong-shaped one fails the type check. An address with a `:name`
 * piece in it needs that piece supplied as `hrefParams`, and this fills it in.
 * That part is not checked by the type — a missing piece throws when the link
 * is drawn.
 *
 * The colon spelling is the one preact-iso matches on, so `/meal/:mealId` is
 * the address the meal route answers. The two address props and what they mean
 * come from `LinkAddressPropsViaColons` rather than being restated here.
 */
export interface PropsForInternalLinkAtom extends LinkAddressPropsViaColons {
	class?: string
	/**
	 * Class to add while this link points at the page on screen. It also covers
	 * a page sitting underneath, which is what keeps `/categories` marked while
	 * a category is being read.
	 *
	 * The routers on the sibling sites work this out themselves; preact-iso
	 * only reports the current address, so `checkIsCurrentPage` below does it
	 * here.
	 */
	activeClass?: string
	children?: ComponentChildren
}

export function InternalLinkAtom({
	href,
	hrefParams,
	class: ownClass = '',
	activeClass = '',
	children,
}: PropsForInternalLinkAtom) {
	const fullAddress = getFullAddressViaColons({ href, hrefParams })
	// Empty outside a location provider, which is every story that does not
	// wrap itself in one. A link still draws and still works; it just never
	// reads as the current page.
	const { path } = useLocation()
	const isCurrentPage = checkIsCurrentPage(path, fullAddress)
	const classes = [ownClass, isCurrentPage ? activeClass : ''].filter(Boolean)
	return (
		<a class={classes.join(' ')} href={fullAddress}>
			{children}
		</a>
	)
}

/**
 * Whether the page on screen is this link's page, or one sitting underneath it.
 *
 * "Underneath" is why the test is not a plain match: `/categories` should stay
 * marked while a single category is being read. It is written as the address
 * plus a slash rather than as a plain starts-with, so that `/` — which every
 * address begins with — marks only the home page, and so that a future
 * `/categories-archive` would not mark `/categories`.
 *
 * @param path - the address on screen, or nothing outside a location provider
 * @param fullAddress - where this link points, with its pieces filled in
 */
function checkIsCurrentPage(
	path: string | undefined,
	fullAddress: string,
): boolean {
	if (!path) return false
	const isSamePage = path === fullAddress
	const isPageUnderneath = path.startsWith(`${fullAddress}/`)
	return isSamePage || isPageUnderneath
}
