// example-site/svelte/src/components/03-organisms/FooterOrganism.svelte
<script>
	import ExternalLinkAtom from '../01-atoms/ExternalLinkAtom.svelte';
</script>

<div class="FooterOrganism border-t-2 border-teal-900 bg-teal-200 p-4 text-center text-black">
	<p>
		Meal data provided by{' '}
		<ExternalLinkAtom href="https://www.themealdb.com/">TheMealDB.com</ExternalLinkAtom>
	</p>
</div>

// example-site/vue/app/components/03-organisms/FooterOrganism.vue
<script setup lang="ts">
import ExternalLinkAtom from '../01-atoms/ExternalLinkAtom.vue'

export interface PropsForFooterOrganism {}

const {} = defineProps<PropsForFooterOrganism>()
</script>

<template>
	<div
		class="FooterOrganism border-t-2 border-teal-900 bg-teal-100 p-4 text-center text-black"
	>
		<p>
			Meal data provided by{{ ' ' }}
			<ExternalLinkAtom href="https://www.themealdb.com/"
				>TheMealDB.com</ExternalLinkAtom
			>
		</p>
	</div>
</template>
