// example-site/src/components/forms/FormDataPreview/FormDataMolecule.tsx
import type { ReactNode } from 'react'
import { FormDataPreviewAtom } from './FormDataPreviewAtom'

interface PropsForFormDataWrapper<FormValues extends Record<string, any>> {
	formValues?: FormValues
	children: ReactNode
}

export function FormDataMolecule<FormValues extends Record<string, any>>({
	formValues,
	children,
}: PropsForFormDataWrapper<FormValues>) {
	return (
		<div className="grid gap-2">
			{children}
			<FormDataPreviewAtom formValues={formValues} />
		</div>
	)
}

// example-site/svelte/src/components/zz-meta-components/FormDataPreview/FormDataMolecule.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import FormDataPreviewAtom from './FormDataPreviewAtom.svelte';

	export interface PropsForFormDataMolecule<FormValues extends Record<string, any>> {
		formValues?: FormValues;
		children?: Snippet;
	}

	const { children, formValues }: PropsForFormDataMolecule<Record<string, any>> = $props();
</script>

<div class="FormDataMolecule grid gap-2">
	{@render children?.()}
	<FormDataPreviewAtom {formValues} />
</div>
