// example-site/svelte/src/components/forms/TextFieldMolecule.svelte
<script lang="ts">
	import { useStore, type AnyFieldApi } from '@tanstack/svelte-form';
	import type { WithField } from './FormTypes';
	import ErrorListMolecule from './ErrorMessages/ErrorListMolecule.svelte';

	export interface PropsForTextFieldMolecule {
		label: string;
		placeholder?: string;
	}

	export type FieldPropsForTextFieldMolecule<FieldApi extends AnyFieldApi> =
		PropsForTextFieldMolecule & WithField<FieldApi>;

	const { label, placeholder, field }: FieldPropsForTextFieldMolecule<AnyFieldApi> = $props();

	const errors = $derived(useStore(field.store, (s) => s.meta.errors));
	const id = $derived(field.name.replace(/\W/g, ''));
	const showErrors = $derived(field.state.meta.isTouched && errors.current?.length > 0);
</script>

<div class="TextFieldMolecule">
	<label for={id} class="mb-1 block text-xl font-bold">
		{label}
		<input
			{id}
			value={field.state.value}
			{placeholder}
			onblur={field.handleBlur}
			oninput={(e) => field.handleChange(e.currentTarget.value)}
			class="w-full rounded-md border border-gray-300 px-4 py-2 focus:ring-2 focus:ring-indigo-500 focus:outline-none"
		/>
	</label>
	{#if showErrors}
		<ErrorListMolecule errors={errors.current} />
	{/if}
</div>

// example-site/react/src/components/forms/TextFieldMolecule/TextFieldMolecule.tsx
import { useStore, type AnyFieldApi } from '@tanstack/react-form'
import { ErrorListMolecule } from '../ErrorMessages/ErrorListMolecule'
import type { WithField } from '../FormTypes'

export interface PropsForTextFieldMolecule {
  label: string
  placeholder?: string
}

export type FieldPropsForTextFieldMolecule<FieldApi extends AnyFieldApi> =
  PropsForTextFieldMolecule & WithField<FieldApi>

export function TextFieldMolecule<FieldApi extends AnyFieldApi>({
  label,
  placeholder,
  field,
}: FieldPropsForTextFieldMolecule<FieldApi>) {
  const errors = useStore(field.store, (s) => s.meta.errors)
  const id = field.name.replace(/\W/g, '')
  const showErrors = field.state.meta.isTouched && errors?.length > 0

  return (
    <div>
      <label htmlFor={id} className="block font-bold mb-1 text-xl">
        {label}
        <input
          id={id}
          value={field.state.value}
          placeholder={placeholder}
          onBlur={field.handleBlur}
          onChange={(e) => field.handleChange(e.target.value)}
          className="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
        />
      </label>
      {showErrors && <ErrorListMolecule errors={errors} />}
    </div>
  )
}
